## Data scraping part

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import pandas as pd

#setup
pd.set_option('display.max_colwidth', 100)

In [98]:
url = "https://www.primeminister.am/en/foreign-visits"
r = requests.get(url)

In [99]:
# saving html of the main page here
doc = BeautifulSoup(r.text)

In [100]:
# finding the last page on a pagination to create links to all pages' links

last_page = int(doc.find_all("li", class_="paging__item ver-top-box")[-1].text.replace("\n", ""))
last_page

23

In [101]:
# Creating a list of all pages

pages = []
for i in range(last_page):
    pages.append(f'https://www.primeminister.am/en/foreign-visits/page/{i+1}/')
pages

['https://www.primeminister.am/en/foreign-visits/page/1/',
 'https://www.primeminister.am/en/foreign-visits/page/2/',
 'https://www.primeminister.am/en/foreign-visits/page/3/',
 'https://www.primeminister.am/en/foreign-visits/page/4/',
 'https://www.primeminister.am/en/foreign-visits/page/5/',
 'https://www.primeminister.am/en/foreign-visits/page/6/',
 'https://www.primeminister.am/en/foreign-visits/page/7/',
 'https://www.primeminister.am/en/foreign-visits/page/8/',
 'https://www.primeminister.am/en/foreign-visits/page/9/',
 'https://www.primeminister.am/en/foreign-visits/page/10/',
 'https://www.primeminister.am/en/foreign-visits/page/11/',
 'https://www.primeminister.am/en/foreign-visits/page/12/',
 'https://www.primeminister.am/en/foreign-visits/page/13/',
 'https://www.primeminister.am/en/foreign-visits/page/14/',
 'https://www.primeminister.am/en/foreign-visits/page/15/',
 'https://www.primeminister.am/en/foreign-visits/page/16/',
 'https://www.primeminister.am/en/foreign-visits/page/17/',
 'https://www.primeminister.am/en/foreign-visits/page/18/',
 'https://www.primeminister.am/en/foreign-visits/page/19/',
 'https://www.primeminister.am/en/foreign-visits/page/20/',
 'https://www.primeminister.am/en/foreign-visits/page/21/',
 'https://www.primeminister.am/en/foreign-visits/page/22/',
 'https://www.primeminister.am/en/foreign-visits/page/23/']

In [227]:
# creating a function to scrape the visit_links from the given page

def page_scraper(page_link):
    r = requests.get(page_link)
    doc = BeautifulSoup(r.text)
    list_of_a = doc.find_all("a", class_="search__result-title db")
    visit_links = [f'https://www.primeminister.am{a.get("href")}' for a in list_of_a]
    return visit_links

In [ ]:
# testing with long texts

page_scraper

In [103]:
# running the fuction on all pages to get direct link to all pages about visits

all_visit_links = []
for page in pages:
    all_visit_links.extend(page_scraper(page))

all_visit_links

['https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Republic-of-the-RF/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/06/13/Nikol-Pashinyan-visiting-Czech-Republic-13.06.25/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/05/15/Nikol-Pashinyan-visiting-Albania./',
 'https://www.primeminister.am/en/foreign-visits/item/2025/05/08/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/04/27/Nikol-Pashinyan-visiting-Estonia/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/03/23/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/13/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/10/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/03/Nikol-Pashinyan-visiting-Vashington/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/01/23/Nikol-Pashinyan-visiting-Switzerland/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/12/13/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/12/07/Nikol-Pashinyan-visiting-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/11/18/Nikol-Pashinyan-visiting-Vatican/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/11/06/Nikol-Pashinyan-visiting-Hungary/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/24/Nikol-Pashinyan-visiting-Kazan/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/07/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/03/Nikol-Pashinyan-visiting-France./',
 'https://www.primeminister.am/en/foreign-visits/item/2024/09/22/Nikol-Pashinyan-visiting-New-York-September-22-27/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/09/16/Nikol-Pashinyan-visited-to-Georgia-16-09-2024/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/30/Nikol-Pashinyan-visit-to-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/17/Nikol-Pashinyan-visit-to-London/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/14/Nikol-Pashinyan-meeting/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/22/Nikol-Pashinyan-visiting-Tehran/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/13/Nikol-Pashinyan-visit-to-Kingdom-of-Denmark/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/08/Nikol-Pashinyan-visit-to-RF/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/04/04/Nikol-Pashinyan-working-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/03/20/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/03/05/Nikol-Pashinyan-visiting-Egypt/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/27/Nikol-Pashinyan-visiting-Greece/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/21/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/16/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/02/Nikol-Pashinyan-visiting-Kazakhstan-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/01/26/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/12/25/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/11/09/Nikol-Pashinyan-visiting-Republic-of-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/26/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/16/Nikol-Pashinyan-visiting-Strasbourg./',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/04/Nikol-Pashinyan-visit-to-Granada/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/07/14/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/07/07/Nikol-Pashinyan-visiting-Georgia-Batumi/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/06/07/Nikol-Pashinyan-visiting-Sochi/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/06/03/Nikol-Pashinyan-visiting-Turkey/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/31/Nikol-Pashinyan-working-visit-Moldova/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/24/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/16/Nikol-Pashinyan-visiting-Republic-of-Iceland/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/13/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/08/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/04/Nikol-Pashinyan-visiting-Czech-Republic/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/03/02/Nikol-Pashinyan-visiting-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/02/16/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/02/02/Nikol-Pashinyan-visiting-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/12/26/Nikol-Pashinyan-visiting-Saint-Petersburg./',
 'https://www.primeminister.am/en/foreign-visits/item/2022/12/09/Nikol-Pashinyan-visit-to-Bishkek/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/11/19/Nikol-Pashinyan-visiting-Tunisia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/11/01/Nikol-Pashinyan-visiting-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/31/Nikol-Pashinyan-visitin-Sochi/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/13/Nikol-Pashinyan-visit-to-Astana/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/07/Nikol-Pashinyan-visitin-St-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/06/Nikol-Pashinyan-visiting-Praha/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/26/Nikol-Pashinyan-Emmanuel-Macron/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/22/Nikol-Pashinyan-visit-to-New-Yourk/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/06/Nikol-Pashinyan-visit-to-Russia-6-9/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/08/31/Nikol-Pashinyan-visit-to-Brussels-31-08/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/08/25/Nikol-Pashinyan-visit-to-the-Kyrgyz-Republic-25-26/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/06/20/Nikol-Pashinyan-visiting-Belarus/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/06/13/Nikol-Pashinyan-visiting-State-of-Qatar/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/22/Nikol-Pashinyan-visit-to-Brussels./',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/16/Nikol-Pashinyan-visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/10/Nikol-Pashinyan-visit-to-Kingdom-of-the-Netherlands/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/04/19/Nikol-Pashinyan-visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/04/05/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/03/08/Nikol-Pashinyan-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/02/24/Nikol-Pashinyan-visit-to-Kazakhstan./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/28/Nikol-Pashinyan-Visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/20/Nikol-Pashinyan-visit-to-Georgia./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/14/Nikol-Pashinyan-visit-to-Brussels./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/11/26/Nikol-Pashinyan-visit-to-Sochi./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/10/12/Nikol-Pashinyan-Vladimir-Putin/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/10/03/Nikol-Pashinyan-visit-to-Lithuania./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/09/15/Nikol-Pashinyan-visit-to-Dushanbe/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/09/08/Nikol-Pashinyan-visit-to-Georgia./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/08/19/Nikol-Pashinyan-visit-to-Kyrgyzstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/08/05/Nikol-Pashinyan-visit-to-Islamic-Republic-of-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/07/07/Nikol-Pashinyan-Vladimir-Putin/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/05/31/Nikol-Pashinyan-visit-to-Paris-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/04/29/Nikol-Pashinyan-visit-to-Kazan/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/04/07/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/02/04/Nikol-Pashinyan-visit-to-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/01/11/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/07/16/Nikol-Pashinyan-visit-to-Minsk/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/03/09/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/03/03/visit-to-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/02/13/Nikol-Pashinyan-visit-to-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/01/31/Nikol-Pashinyan-visit-to-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/12/20/Nikol-Pashinyan-visit-to-Saint-Peterburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/27/visit-to-Kyrgyz-Republic/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/20/Nikol-Pashinyan-visit-to-Italia/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/11/Nikol-Pashinyan-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/10/25/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/10/10/Nikol-Pashinyan-visit-Turkmenistan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/09/22/Nikol-Pashinyn-visit-to-USA/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/08/08/Nikol-Pashinyan-visit-to-Kyrgyzstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/07/07/Nikol-Pashinyan-visit-to-Singapore/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/07/04/Nikol-Pashinyan-visit-to-Vietnam/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/06/06/visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/28/Khazakhstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/14/visit-to-Chine/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/12/visit-to-Luxembourg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/04/10/Nikol-Pashinyan-visit-to-Strasburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/03/28/Nikol-Pashinyan-visit-to-Vienna/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/03/04/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/02/27/visit-to-Iran./',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/31/visit-to-Federal-Republic-of-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/25/Nikol-Pashinyan-Visit-to-Russia-Federation/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/21/Nikol-Pashinyan-visit-to-Swiss-Confederation/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/15/Nikol-Pashinyan-Mamouka-Bakhtadze/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/12/27/visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/12/06/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/11/10/Nikol-Pashinyan-working-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/11/08/Nikol-Pashinyan-Kazakhstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/10/20/Nikol-Pashinyan-visit-to-Lebanon/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/10/05/Nikol-Pashinyan-visit-to-France-05-06.10/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/27/Nikol-Pashinyan-working-visit-to-Dushanbe/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/24/Nikol-Pashinyan-working-visit-New-York/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/13/Nikol-Pashinyan-visit-to-France-13-14/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/08/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/07/26/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/07/11/Nikol-Pashinyan-visit-to-Kingdom-of-Belgium/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/06/13/Nikol-Pashinyan-Visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/05/30/Prime-Minister-Nikol-Pashinyans-official-visit-to-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/05/13/Prime-Minister-Nikol-Pashinyans-working-visit-to-Russia/']

In [104]:
len(all_visit_links)

135

In [228]:
# creating a function to scrape the visit_links from the given page


def data_parser(link):
    visit_data = {}
    r = requests.get(link)
    doc = BeautifulSoup(r.text)
    visit_data['link']=link
    visit_data['title']=doc.find("h3").text
    visit_data['date']=doc.find("div", class_="search__date fs12").text
    try:
        visit_data['text']=doc.find("div", class_="news-text").text.replace("\n", "")
    except:
        visit_data['text']="no text in the"
    return visit_data

In [229]:
data_parser("https://www.primeminister.am/en/foreign-visits/item/2020/02/13/Nikol-Pashinyan-visit-to-Germany/")

{'link': 'https://www.primeminister.am/en/foreign-visits/item/2020/02/13/Nikol-Pashinyan-visit-to-Germany/',
 'title': 'PM arrives in Germany on working visit',
 'date': '13.02.2020 - 15.02.2020',

In [114]:
data = []
for link in all_visit_links:
    data.append(data_parser(link))
df = pd.DataFrame(data)
df

,link,title,date,text
0,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,24.07.2025 - 25.07.2025,Nikol Pashinyan arrived in the Altai Republic ...
1,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
2,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
3,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in...
4,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in...
...,...,...,...,...
130,https://www.primeminister.am/en/foreign-visits...,Nikol Pashinyan attends Eurasian Intergovernme...,26.07.2018 - 27.07.2018,Prime Minister Nikol Pashinyan arrived in St. ...
131,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan's working visit...,11.07.2018 - 12.07.2018,Prime Minister Nikol Pashinyan arrived in the ...
132,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan is away to the ...,13.06.2018 - 14.06.2018,"On a working visit to Russia, Prime Minister N..."
133,https://www.primeminister.am/en/foreign-visits...,Prime Minister Nikol Pashinyan’s official visi...,30.05.2018 - 31.05.2018,"Led by Prime Minister Nikol Pashinyan, the Ar..."
134,https://www.primeminister.am/en/foreign-visits...,Working visit of Prime Minister Nikol Pashinya...,13.05.2018 - 14.05.2018,Prime Minister Nikol Pashinyan arrived in the ...

In [115]:
df.to_csv("scraped_data_en.csv", index=False)

## Analysis part 1

##### Here I'm using AI to grab the name of country and city of visit form description

In [345]:
from openai import OpenAI
import time
import os

In [346]:
from dotenv import load_dotenv

In [347]:
load_dotenv(override=True)
api_key = os.environ['OPENAI_API_KEY_LEDE']

In [348]:
client = OpenAI(api_key=api_key)

In [349]:
# opening data from csv file

df = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/scraped_data_en.csv", index_col=False)

In [350]:
df

,link,title,date,text
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako..."
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni..."
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...
3,https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/,Prime Minister Nikol Pashinyan's working visit to the UAE,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in the United Arab Emirates on a working visit.The A...
4,https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/,Prime Minister Nikol Pashinyan's working visit to Türkiye,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in Türkiye on a working visit.\rThe Prime Minister w...
...,...,...,...,...
130,https://www.primeminister.am/en/foreign-visits/item/2018/07/26/Nikol-Pashinyan-visit-to-Saint-Pe...,Nikol Pashinyan attends Eurasian Intergovernmental Council meeting in St Petersburg,26.07.2018 - 27.07.2018,Prime Minister Nikol Pashinyan arrived in St. Petersburg on a working visit. The Head of Governm...
131,https://www.primeminister.am/en/foreign-visits/item/2018/07/11/Nikol-Pashinyan-visit-to-Kingdom-...,Prime Minister Nikol Pashinyan's working visit to the Kingdom of Belgium,11.07.2018 - 12.07.2018,Prime Minister Nikol Pashinyan arrived in the Kingdom of Belgium on a working visit. The Premier...
132,https://www.primeminister.am/en/foreign-visits/item/2018/06/13/Nikol-Pashinyan-Visit-to-Russia/,Prime Minister Nikol Pashinyan is away to the Russian Federation on a working visit,13.06.2018 - 14.06.2018,"On a working visit to Russia, Prime Minister Nikol Pashinyan met with RF President Vladimir Puti..."
133,https://www.primeminister.am/en/foreign-visits/item/2018/05/30/Prime-Minister-Nikol-Pashinyans-o...,Prime Minister Nikol Pashinyan’s official visit to Georgia,30.05.2018 - 31.05.2018,"Led by Prime Minister Nikol Pashinyan, the Armenian government delegation arrived in Georgia on..."
134,https://www.primeminister.am/en/foreign-visits/item/2018/05/13/Prime-Minister-Nikol-Pashinyans-w...,Working visit of Prime Minister Nikol Pashinyan to the Russian Federation,13.05.2018 - 14.05.2018,Prime Minister Nikol Pashinyan arrived in the Russian Federation on a working visit. From Sochi ...

In [ ]:
import pandas as pd
from openai import OpenAI
import tiktoken  # for counting tokens

# Tokenizer for gpt-3.5-turbo
encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")

MAX_TOKENS = 16385
SAFETY_MARGIN = 500  # leave room for system prompt, etc.
MAX_INPUT_TOKENS = MAX_TOKENS - SAFETY_MARGIN

def truncate_text(text, max_tokens=MAX_INPUT_TOKENS):
    """Truncate text to fit within allowed token limit and return flag."""
    tokens = encoding.encode(text)
    truncated = False
    if len(tokens) > max_tokens:
        tokens = tokens[:max_tokens]
        truncated = True
    return encoding.decode(tokens), truncated

def classify(text):
    try:
        short_text, truncated = truncate_text(text)
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Please read the text abot Armenina PM Nikol Pashinyan's officials vistis abroad."
                        "Identify the country and city/cities that he visit.\n"
                        "Return your answer in this exact format:\n"
                        "Country name | City1;City2;City3\n"
                        "- Put the international country name, without abbreviations\n"
                        "- Country of visit can not be Armenia!! Please do not write Armenia as a country"
                        "- If country unknown, write: manual check\n"
                        "- If city unknown, write: manual check\n"
                        "- Do not add any extra words to the answer."
                    )
                },
                {"role": "user", "content": short_text}
            ],
            temperature=0,
            top_p=1,
            max_tokens=30
        )
        return response.choices[0].message.content.strip(), truncated
    except Exception as e:
        print(f"Error with message: {text[:50]}... — {e}")
        return "error | error", False

# Load dataset
df = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/scraped_data_en.csv")

# Apply classifier & store raw result + truncation flag
df[["raw_result", "was_truncated"]] = df["text"].apply(
    lambda msg: pd.Series(classify(str(msg)))
)

# Split raw_result into country and city columns
split_cols = df["raw_result"].str.split("|", n=1, expand=True)
df["country"] = split_cols[0].str.strip().str.lower()
df["city"] = split_cols[1].str.strip().str.lower() if split_cols.shape[1] > 1 else None

# Save results
output_path = "/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/classified_data.csv"
df.to_csv(output_path, index=False)

print(f"Classification completed. Results saved to: {output_path}")

Classification completed. Results saved to: /Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/new_classified_data.csv

## Data cleaning part

In [352]:
# opening 

df = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/new_classified_data.csv", index_col=False)
df.head()

,link,title,date,text,raw_result,was_truncated,country,city
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako...",Russian Federation | Gorno-Altaysk,False,russian federation,gorno-altaysk
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni...",France | Paris,False,france,paris
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...,Belgium | Brussels,False,belgium,brussels
3,https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/,Prime Minister Nikol Pashinyan's working visit to the UAE,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in the United Arab Emirates on a working visit.The A...,United Arab Emirates | Abu Dhabi,False,united arab emirates,abu dhabi
4,https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/,Prime Minister Nikol Pashinyan's working visit to Türkiye,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in Türkiye on a working visit.\rThe Prime Minister w...,Türkiye | Istanbul,False,türkiye,istanbul

In [354]:
#creating start and end dates

df[['start_date', 'end_date']] = df['date'].str.split(' - ', expand=True)
df.head()

,link,title,date,text,raw_result,was_truncated,country,city,start_date,end_date
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako...",Russian Federation | Gorno-Altaysk,False,russian federation,gorno-altaysk,24.07.2025,25.07.2025
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni...",France | Paris,False,france,paris,14.07.2025,14.07.2025
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...,Belgium | Brussels,False,belgium,brussels,14.07.2025,14.07.2025
3,https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/,Prime Minister Nikol Pashinyan's working visit to the UAE,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in the United Arab Emirates on a working visit.The A...,United Arab Emirates | Abu Dhabi,False,united arab emirates,abu dhabi,09.07.2025,10.07.2025
4,https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/,Prime Minister Nikol Pashinyan's working visit to Türkiye,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in Türkiye on a working visit.\rThe Prime Minister w...,Türkiye | Istanbul,False,türkiye,istanbul,20.06.2025,20.06.2025

In [355]:
# turning into datetime format
 
df['start_date'] = pd.to_datetime(df['start_date'], format='%d.%m.%Y')
df['end_date'] = pd.to_datetime(df['end_date'], format='%d.%m.%Y')

In [278]:
# splitting the City_country column into two separate columns and stripping to remove spaces

# Safely split into two columns, fill missing values
split_cols = df['city_country'].str.split(';', n=1, expand=True)

df['city'] = split_cols[0].str.strip()
df['country'] = split_cols[1].str.strip() if split_cols.shape[1] > 1 else ""

In [356]:
df.head(3)

,link,title,date,text,raw_result,was_truncated,country,city,start_date,end_date
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako...",Russian Federation | Gorno-Altaysk,False,russian federation,gorno-altaysk,2025-07-24,2025-07-25
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni...",France | Paris,False,france,paris,2025-07-14,2025-07-14
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...,Belgium | Brussels,False,belgium,brussels,2025-07-14,2025-07-14

In [301]:
# calculating the difference of dates

df['days_diff'] = (pd.to_datetime(df['end_date']) - pd.to_datetime(df['start_date'])).dt.days
df.head(3)

,link,title,date,text,raw_result,was_truncated,country,city,start_date,end_date,days_diff
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako...",Russia | Gorno-Altaysk;Altai,False,russia,gorno-altaysk;altai,2025-07-24,2025-07-25,1.0
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni...",France | Paris,False,france,paris,2025-07-14,2025-07-14,0.0
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...,Belgium | Brussels; manual check,False,belgium,brussels; manual check,2025-07-14,2025-07-14,0.0

In [365]:
# adding year to data

df['year'] = pd.to_datetime(df['start_date']).dt.year
df

,link,title,date,text,raw_result,was_truncated,country,city,start_date,end_date,year
0,https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Re...,Prime Minister Nikol Pashinyan's working visit to the Altai Republic of the Russian Federation,24.07.2025 - 25.07.2025,"Nikol Pashinyan arrived in the Altai Republic of the Russian Federation with his wife, Anna Hako...",Russian Federation | Gorno-Altaysk,False,russia,gorno-altaysk,2025-07-24,2025-07-25,2025
1,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/,Prime Minister Nikol Pashinyan's working visit to the French Republic,14.07.2025 - 14.07.2025,"Prime Minister Nikol Pashinyan has arrived in Paris, France on a working visit.Prime Minister Ni...",France | Paris,False,france,paris,2025-07-14,2025-07-14,2025
2,https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/,Prime Minister Nikol Pashinyan's working visit to Brussels,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in Brussels on a working visit.A trilateral meeting w...,Belgium | Brussels,False,belgium,brussels,2025-07-14,2025-07-14,2025
3,https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/,Prime Minister Nikol Pashinyan's working visit to the UAE,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in the United Arab Emirates on a working visit.The A...,United Arab Emirates | Abu Dhabi,False,united arab emirates,abu dhabi,2025-07-09,2025-07-10,2025
4,https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/,Prime Minister Nikol Pashinyan's working visit to Türkiye,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in Türkiye on a working visit.\rThe Prime Minister w...,Türkiye | Istanbul,False,turkey,istanbul,2025-06-20,2025-06-20,2025
...,...,...,...,...,...,...,...,...,...,...,...
130,https://www.primeminister.am/en/foreign-visits/item/2018/07/26/Nikol-Pashinyan-visit-to-Saint-Pe...,Nikol Pashinyan attends Eurasian Intergovernmental Council meeting in St Petersburg,26.07.2018 - 27.07.2018,Prime Minister Nikol Pashinyan arrived in St. Petersburg on a working visit. The Head of Governm...,Russia | Saint Petersburg,False,russia,saint petersburg,2018-07-26,2018-07-27,2018
131,https://www.primeminister.am/en/foreign-visits/item/2018/07/11/Nikol-Pashinyan-visit-to-Kingdom-...,Prime Minister Nikol Pashinyan's working visit to the Kingdom of Belgium,11.07.2018 - 12.07.2018,Prime Minister Nikol Pashinyan arrived in the Kingdom of Belgium on a working visit. The Premier...,Belgium | Brussels,False,belgium,brussels,2018-07-11,2018-07-12,2018
132,https://www.primeminister.am/en/foreign-visits/item/2018/06/13/Nikol-Pashinyan-Visit-to-Russia/,Prime Minister Nikol Pashinyan is away to the Russian Federation on a working visit,13.06.2018 - 14.06.2018,"On a working visit to Russia, Prime Minister Nikol Pashinyan met with RF President Vladimir Puti...",Russia | Moscow;Sochi,False,russia,moscow;sochi,2018-06-13,2018-06-14,2018
133,https://www.primeminister.am/en/foreign-visits/item/2018/05/30/Prime-Minister-Nikol-Pashinyans-o...,Prime Minister Nikol Pashinyan’s official visit to Georgia,30.05.2018 - 31.05.2018,"Led by Prime Minister Nikol Pashinyan, the Armenian government delegation arrived in Georgia on...",Georgia | Tbilisi;Poka;Gandza;Satkha;Ninotsminda;Akhalkalaki,False,georgia,tbilisi;poka;gandza;satkha;ninotsminda;akhalkalaki,2018-05-30,2018-05-31,2018
134,https://www.primeminister.am/en/foreign-visits/item/2018/05/13/Prime-Minister-Nikol-Pashinyans-w...,Working visit of Prime Minister Nikol Pashinyan to the Russian Federation,13.05.2018 - 14.05.2018,Prime Minister Nikol Pashinyan arrived in the Russian Federation on a working visit. From Sochi ...,Russian Federation | Sochi;Adler,False,russia,sochi;adler,2018-05-13,2018-05-14,2018

In [366]:
pd.pivot_table(
    df,
    values='link',            # the column to "count"
    index='country',          # rows
    aggfunc='count',           # counts non-null values (like COUNTA)
).sort_values(by='link', ascending=False)

                      link
country
russia                  33
france                  15
belgium                 12
georgia                 10
kazakhstan               8
germany                  7
united states            5
kyrgyzstan               5
iran                     5
czech republic           3
tajikistan               2
switzerland              2
turkey                   2
belarus                  2
singapore                1
spain                    1
tunisia                  1
united kingdom           1
turkmenistan             1
qatar                    1
vatican                  1
united arab emirates     1
albania                  1
lebanon                  1
netherlands              1
moldova                  1
luxembourg               1
lithuania                1
austria                  1
italy                    1
iceland                  1
hungary                  1
greece                   1
estonia                  1
egypt                    1
denmark                  1
china                    1
vietnam                  1

In [367]:
# cleaning dataframe 

df['country'] = df['country'].replace({'russian federation': 'russia', 
                                       'türkiye':'turkey',
                                       'united states of america':'united states',
                                       'holy see':'vatican',
                                       "people's republic of china":'china',
                                       })

In [371]:
pd.pivot_table(
    df,
    values='link',            # the column to "count"
    index='country',          # rows
    aggfunc='count',           # counts non-null values (like COUNTA)
).sort_values(by='link', ascending=False)

                      link
country
russia                  33
france                  15
belgium                 12
georgia                 10
kazakhstan               8
germany                  7
united states            5
kyrgyzstan               5
iran                     5
czech republic           3
tajikistan               2
switzerland              2
turkey                   2
belarus                  2
singapore                1
spain                    1
tunisia                  1
united kingdom           1
turkmenistan             1
qatar                    1
vatican                  1
united arab emirates     1
albania                  1
lebanon                  1
netherlands              1
moldova                  1
luxembourg               1
lithuania                1
austria                  1
italy                    1
iceland                  1
hungary                  1
greece                   1
estonia                  1
egypt                    1
denmark                  1
china                    1
vietnam                  1

In [372]:

# Pivot table: count 'link' by country and year
pivot = pd.pivot_table(
    df,
    values='link',             # the column to count
    index='country',           # rows
    columns='year',            # years as columns
    aggfunc='count',           # counts non-null values
    fill_value=0               # replace NaN with 0
).sort_values(by=df['year'].max(), ascending=False)  # sort by latest year column

In [373]:
pivot

year                  2018  2019  2020  2021  2022  2023  2024  2025
country
russia                   6     4     0     7     6     4     4     2
france                   3     2     0     1     2     2     3     2
albania                  0     0     0     0     0     0     0     1
estonia                  0     0     0     0     0     0     0     1
switzerland              0     1     0     0     0     0     0     1
turkey                   0     0     0     0     0     1     0     1
georgia                  1     1     1     2     0     2     2     1
germany                  0     1     1     0     0     2     2     1
united arab emirates     0     0     0     0     0     0     0     1
czech republic           0     0     0     0     1     1     0     1
united states            1     1     0     0     1     0     1     1
belgium                  1     1     1     1     3     2     2     1
united kingdom           0     0     0     0     0     0     1     0
moldova                  0     0     0     0     0     1     0     0
turkmenistan             0     1     0     0     0     0     0     0
tunisia                  0     0     0     0     1     0     0     0
tajikistan               1     0     0     1     0     0     0     0
spain                    0     0     0     0     0     1     0     0
singapore                0     1     0     0     0     0     0     0
vatican                  0     0     0     0     0     0     1     0
qatar                    0     0     0     0     1     0     0     0
netherlands              0     0     0     0     1     0     0     0
lebanon                  1     0     0     0     0     0     0     0
luxembourg               0     1     0     0     0     0     0     0
lithuania                0     0     0     1     0     0     0     0
austria                  0     1     0     0     0     0     0     0
kyrgyzstan               0     2     0     1     2     0     0     0
kazakhstan               1     1     1     1     2     1     1     0
italy                    0     1     0     0     0     0     0     0
iran                     0     1     0     1     1     0     2     0
iceland                  0     0     0     0     0     1     0     0
hungary                  0     0     0     0     0     0     1     0
greece                   0     0     0     0     0     0     1     0
egypt                    0     0     0     0     0     0     1     0
denmark                  0     0     0     0     0     0     1     0
china                    0     1     0     0     0     0     0     0
belarus                  0     0     1     0     1     0     0     0
vietnam                  0     1     0     0     0     0     0     0

In [375]:
df.to_csv('cleaned_data_with_countries.csv')

## Analysis part 2

##### Here I'm using AI to summarize the visit