## Data scraping part

In [55]:
import requests
import pandas as pd 
from bs4 import BeautifulSoup
import pandas as pd

In [56]:
url = "https://www.primeminister.am/en/foreign-visits"
r = requests.get(url)

In [57]:
# saving html of the main page here
doc = BeautifulSoup(r.text)

In [58]:
# finding the last page on a pagination to create links to all pages' links

last_page = int(doc.find_all("li", class_="paging__item ver-top-box")[-1].text.replace("\n", ""))
last_page

23

In [59]:
# Creating a list of all pages

pages = []
for i in range(last_page):
    pages.append(f'https://www.primeminister.am/en/foreign-visits/page/{i+1}/')
pages

['https://www.primeminister.am/en/foreign-visits/page/1/',
 'https://www.primeminister.am/en/foreign-visits/page/2/',
 'https://www.primeminister.am/en/foreign-visits/page/3/',
 'https://www.primeminister.am/en/foreign-visits/page/4/',
 'https://www.primeminister.am/en/foreign-visits/page/5/',
 'https://www.primeminister.am/en/foreign-visits/page/6/',
 'https://www.primeminister.am/en/foreign-visits/page/7/',
 'https://www.primeminister.am/en/foreign-visits/page/8/',
 'https://www.primeminister.am/en/foreign-visits/page/9/',
 'https://www.primeminister.am/en/foreign-visits/page/10/',
 'https://www.primeminister.am/en/foreign-visits/page/11/',
 'https://www.primeminister.am/en/foreign-visits/page/12/',
 'https://www.primeminister.am/en/foreign-visits/page/13/',
 'https://www.primeminister.am/en/foreign-visits/page/14/',
 'https://www.primeminister.am/en/foreign-visits/page/15/',
 'https://www.primeminister.am/en/foreign-visits/page/16/',
 'https://www.primeminister.am/en/foreign-visits/page/17/',
 'https://www.primeminister.am/en/foreign-visits/page/18/',
 'https://www.primeminister.am/en/foreign-visits/page/19/',
 'https://www.primeminister.am/en/foreign-visits/page/20/',
 'https://www.primeminister.am/en/foreign-visits/page/21/',
 'https://www.primeminister.am/en/foreign-visits/page/22/',
 'https://www.primeminister.am/en/foreign-visits/page/23/']

In [60]:
# creating a function to scrape the visit_links from the given page

def page_scraper(page_link):
    r = requests.get(page_link)
    doc = BeautifulSoup(r.text)
    list_of_a = doc.find_all("a", class_="search__result-title db")
    visit_links = [f'https://www.primeminister.am{a.get("href")}' for a in list_of_a]
    return visit_links

In [61]:
# running the fuction on all pages to get direct link to all pages about visits

all_visit_links = []
for page in pages:
    all_visit_links.extend(page_scraper(page))

all_visit_links

['https://www.primeminister.am/en/foreign-visits/item/2025/07/24/Nikol-Pashinyan-visiting-Altai-Republic-of-the-RF/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/14/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/07/09/Nikol-Pashinyan-visiting-UAE/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/06/20/Nikol-Pashinyan-visiting-Turkiye/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/06/13/Nikol-Pashinyan-visiting-Czech-Republic-13.06.25/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/05/15/Nikol-Pashinyan-visiting-Albania./',
 'https://www.primeminister.am/en/foreign-visits/item/2025/05/08/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/04/27/Nikol-Pashinyan-visiting-Estonia/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/03/23/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/13/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/10/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/02/03/Nikol-Pashinyan-visiting-Vashington/',
 'https://www.primeminister.am/en/foreign-visits/item/2025/01/23/Nikol-Pashinyan-visiting-Switzerland/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/12/13/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/12/07/Nikol-Pashinyan-visiting-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/11/18/Nikol-Pashinyan-visiting-Vatican/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/11/06/Nikol-Pashinyan-visiting-Hungary/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/24/Nikol-Pashinyan-visiting-Kazan/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/07/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/10/03/Nikol-Pashinyan-visiting-France./',
 'https://www.primeminister.am/en/foreign-visits/item/2024/09/22/Nikol-Pashinyan-visiting-New-York-September-22-27/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/09/16/Nikol-Pashinyan-visited-to-Georgia-16-09-2024/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/30/Nikol-Pashinyan-visit-to-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/17/Nikol-Pashinyan-visit-to-London/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/07/14/Nikol-Pashinyan-meeting/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/22/Nikol-Pashinyan-visiting-Tehran/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/13/Nikol-Pashinyan-visit-to-Kingdom-of-Denmark/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/05/08/Nikol-Pashinyan-visit-to-RF/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/04/04/Nikol-Pashinyan-working-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/03/20/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/03/05/Nikol-Pashinyan-visiting-Egypt/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/27/Nikol-Pashinyan-visiting-Greece/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/21/Nikol-Pashinyan-visiting-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/16/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/02/02/Nikol-Pashinyan-visiting-Kazakhstan-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2024/01/26/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/12/25/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/11/09/Nikol-Pashinyan-visiting-Republic-of-France/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/26/Nikol-Pashinyan-visiting-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/16/Nikol-Pashinyan-visiting-Strasbourg./',
 'https://www.primeminister.am/en/foreign-visits/item/2023/10/04/Nikol-Pashinyan-visit-to-Granada/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/07/14/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/07/07/Nikol-Pashinyan-visiting-Georgia-Batumi/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/06/07/Nikol-Pashinyan-visiting-Sochi/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/06/03/Nikol-Pashinyan-visiting-Turkey/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/31/Nikol-Pashinyan-working-visit-Moldova/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/24/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/16/Nikol-Pashinyan-visiting-Republic-of-Iceland/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/13/Nikol-Pashinyan-visiting-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/08/Nikol-Pashinyan-visiting-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/05/04/Nikol-Pashinyan-visiting-Czech-Republic/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/03/02/Nikol-Pashinyan-visiting-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/02/16/Nikol-Pashinyan-visiting-Munich/',
 'https://www.primeminister.am/en/foreign-visits/item/2023/02/02/Nikol-Pashinyan-visiting-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/12/26/Nikol-Pashinyan-visiting-Saint-Petersburg./',
 'https://www.primeminister.am/en/foreign-visits/item/2022/12/09/Nikol-Pashinyan-visit-to-Bishkek/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/11/19/Nikol-Pashinyan-visiting-Tunisia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/11/01/Nikol-Pashinyan-visiting-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/31/Nikol-Pashinyan-visitin-Sochi/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/13/Nikol-Pashinyan-visit-to-Astana/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/07/Nikol-Pashinyan-visitin-St-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/10/06/Nikol-Pashinyan-visiting-Praha/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/26/Nikol-Pashinyan-Emmanuel-Macron/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/22/Nikol-Pashinyan-visit-to-New-Yourk/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/09/06/Nikol-Pashinyan-visit-to-Russia-6-9/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/08/31/Nikol-Pashinyan-visit-to-Brussels-31-08/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/08/25/Nikol-Pashinyan-visit-to-the-Kyrgyz-Republic-25-26/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/06/20/Nikol-Pashinyan-visiting-Belarus/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/06/13/Nikol-Pashinyan-visiting-State-of-Qatar/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/22/Nikol-Pashinyan-visit-to-Brussels./',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/16/Nikol-Pashinyan-visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/05/10/Nikol-Pashinyan-visit-to-Kingdom-of-the-Netherlands/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/04/19/Nikol-Pashinyan-visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/04/05/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/03/08/Nikol-Pashinyan-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2022/02/24/Nikol-Pashinyan-visit-to-Kazakhstan./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/28/Nikol-Pashinyan-Visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/20/Nikol-Pashinyan-visit-to-Georgia./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/12/14/Nikol-Pashinyan-visit-to-Brussels./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/11/26/Nikol-Pashinyan-visit-to-Sochi./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/10/12/Nikol-Pashinyan-Vladimir-Putin/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/10/03/Nikol-Pashinyan-visit-to-Lithuania./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/09/15/Nikol-Pashinyan-visit-to-Dushanbe/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/09/08/Nikol-Pashinyan-visit-to-Georgia./',
 'https://www.primeminister.am/en/foreign-visits/item/2021/08/19/Nikol-Pashinyan-visit-to-Kyrgyzstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/08/05/Nikol-Pashinyan-visit-to-Islamic-Republic-of-Iran/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/07/07/Nikol-Pashinyan-Vladimir-Putin/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/05/31/Nikol-Pashinyan-visit-to-Paris-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/04/29/Nikol-Pashinyan-visit-to-Kazan/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/04/07/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/02/04/Nikol-Pashinyan-visit-to-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2021/01/11/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/07/16/Nikol-Pashinyan-visit-to-Minsk/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/03/09/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/03/03/visit-to-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/02/13/Nikol-Pashinyan-visit-to-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2020/01/31/Nikol-Pashinyan-visit-to-Almaty/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/12/20/Nikol-Pashinyan-visit-to-Saint-Peterburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/27/visit-to-Kyrgyz-Republic/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/20/Nikol-Pashinyan-visit-to-Italia/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/11/11/Nikol-Pashinyan-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/10/25/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/10/10/Nikol-Pashinyan-visit-Turkmenistan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/09/22/Nikol-Pashinyn-visit-to-USA/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/08/08/Nikol-Pashinyan-visit-to-Kyrgyzstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/07/07/Nikol-Pashinyan-visit-to-Singapore/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/07/04/Nikol-Pashinyan-visit-to-Vietnam/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/06/06/visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/28/Khazakhstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/14/visit-to-Chine/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/05/12/visit-to-Luxembourg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/04/10/Nikol-Pashinyan-visit-to-Strasburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/03/28/Nikol-Pashinyan-visit-to-Vienna/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/03/04/Nikol-Pashinyan-visit-to-Brussels/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/02/27/visit-to-Iran./',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/31/visit-to-Federal-Republic-of-Germany/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/25/Nikol-Pashinyan-Visit-to-Russia-Federation/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/21/Nikol-Pashinyan-visit-to-Swiss-Confederation/',
 'https://www.primeminister.am/en/foreign-visits/item/2019/01/15/Nikol-Pashinyan-Mamouka-Bakhtadze/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/12/27/visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/12/06/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/11/10/Nikol-Pashinyan-working-visit-to-Paris/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/11/08/Nikol-Pashinyan-Kazakhstan/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/10/20/Nikol-Pashinyan-visit-to-Lebanon/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/10/05/Nikol-Pashinyan-visit-to-France-05-06.10/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/27/Nikol-Pashinyan-working-visit-to-Dushanbe/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/24/Nikol-Pashinyan-working-visit-New-York/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/13/Nikol-Pashinyan-visit-to-France-13-14/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/09/08/Nikol-Pashinyan-visit-to-Moscow/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/07/26/Nikol-Pashinyan-visit-to-Saint-Petersburg/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/07/11/Nikol-Pashinyan-visit-to-Kingdom-of-Belgium/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/06/13/Nikol-Pashinyan-Visit-to-Russia/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/05/30/Prime-Minister-Nikol-Pashinyans-official-visit-to-Georgia/',
 'https://www.primeminister.am/en/foreign-visits/item/2018/05/13/Prime-Minister-Nikol-Pashinyans-working-visit-to-Russia/']

In [62]:
len(all_visit_links)

135

In [63]:
# creating a function to scrape the visit_links from the given page


def data_parser(link):
    visit_data = {}
    r = requests.get(link)
    doc = BeautifulSoup(r.text)
    visit_data['link']=doc.find("h3").text
    visit_data['date']=doc.find("div", class_="search__date fs12").text
    try:
        visit_data['text']=doc.find("div", class_="news-text").text.replace("\n", "")
    except:
        visit_data['text']="no text in the"
    return visit_data

In [64]:
data = []
for link in all_visit_links:
    data.append(data_parser(link))
df = pd.DataFrame(data)
df

,link,date,text
0,Prime Minister Nikol Pashinyan's working visit...,24.07.2025 - 25.07.2025,Nikol Pashinyan arrived in the Altai Republic ...
1,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
2,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
3,Prime Minister Nikol Pashinyan's working visit...,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in...
4,Prime Minister Nikol Pashinyan's working visit...,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in...
...,...,...,...
130,Nikol Pashinyan attends Eurasian Intergovernme...,26.07.2018 - 27.07.2018,Prime Minister Nikol Pashinyan arrived in St. ...
131,Prime Minister Nikol Pashinyan's working visit...,11.07.2018 - 12.07.2018,Prime Minister Nikol Pashinyan arrived in the ...
132,Prime Minister Nikol Pashinyan is away to the ...,13.06.2018 - 14.06.2018,"On a working visit to Russia, Prime Minister N..."
133,Prime Minister Nikol Pashinyan’s official visi...,30.05.2018 - 31.05.2018,"Led by Prime Minister Nikol Pashinyan, the Ar..."
134,Working visit of Prime Minister Nikol Pashinya...,13.05.2018 - 14.05.2018,Prime Minister Nikol Pashinyan arrived in the ...

In [65]:
df.to_csv("scraped_data_en.csv")

## Data cleaning part

In [68]:
df.head()

,link,date,text
0,Prime Minister Nikol Pashinyan's working visit...,24.07.2025 - 25.07.2025,Nikol Pashinyan arrived in the Altai Republic ...
1,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
2,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...
3,Prime Minister Nikol Pashinyan's working visit...,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in...
4,Prime Minister Nikol Pashinyan's working visit...,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in...

In [ ]:
df[['col1', 'col2']] = df['column_name'].str.split(',', expand=True)

0      24.07.2025 - 25.07.2025
1      14.07.2025 - 14.07.2025
2      14.07.2025 - 14.07.2025
3      09.07.2025 - 10.07.2025
4      20.06.2025 - 20.06.2025
                ...
130    26.07.2018 - 27.07.2018
131    11.07.2018 - 12.07.2018
132    13.06.2018 - 14.06.2018
133    30.05.2018 - 31.05.2018
134    13.05.2018 - 14.05.2018
Name: date, Length: 135, dtype: object

In [72]:
df[['start_date', 'end_date']] = df['date'].str.split(' - ', expand=True)
df

,link,date,text,start_date,end_date
0,Prime Minister Nikol Pashinyan's working visit...,24.07.2025 - 25.07.2025,Nikol Pashinyan arrived in the Altai Republic ...,24.07.2025,25.07.2025
1,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...,14.07.2025,14.07.2025
2,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...,14.07.2025,14.07.2025
3,Prime Minister Nikol Pashinyan's working visit...,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in...,09.07.2025,10.07.2025
4,Prime Minister Nikol Pashinyan's working visit...,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in...,20.06.2025,20.06.2025
...,...,...,...,...,...
130,Nikol Pashinyan attends Eurasian Intergovernme...,26.07.2018 - 27.07.2018,Prime Minister Nikol Pashinyan arrived in St. ...,26.07.2018,27.07.2018
131,Prime Minister Nikol Pashinyan's working visit...,11.07.2018 - 12.07.2018,Prime Minister Nikol Pashinyan arrived in the ...,11.07.2018,12.07.2018
132,Prime Minister Nikol Pashinyan is away to the ...,13.06.2018 - 14.06.2018,"On a working visit to Russia, Prime Minister N...",13.06.2018,14.06.2018
133,Prime Minister Nikol Pashinyan’s official visi...,30.05.2018 - 31.05.2018,"Led by Prime Minister Nikol Pashinyan, the Ar...",30.05.2018,31.05.2018
134,Working visit of Prime Minister Nikol Pashinya...,13.05.2018 - 14.05.2018,Prime Minister Nikol Pashinyan arrived in the ...,13.05.2018,14.05.2018

In [73]:
df['start_date'] = pd.to_datetime(df['start_date'], format='%d.%m.%Y')
df['end_date'] = pd.to_datetime(df['end_date'], format='%d.%m.%Y')

In [75]:
df.head()

,link,date,text,start_date,end_date
0,Prime Minister Nikol Pashinyan's working visit...,24.07.2025 - 25.07.2025,Nikol Pashinyan arrived in the Altai Republic ...,2025-07-24,2025-07-25
1,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...,2025-07-14,2025-07-14
2,Prime Minister Nikol Pashinyan's working visit...,14.07.2025 - 14.07.2025,Prime Minister Nikol Pashinyan has arrived in ...,2025-07-14,2025-07-14
3,Prime Minister Nikol Pashinyan's working visit...,09.07.2025 - 10.07.2025,Prime Minister Nikol Pashinyan has arrived in...,2025-07-09,2025-07-10
4,Prime Minister Nikol Pashinyan's working visit...,20.06.2025 - 20.06.2025,Prime Minister Nikol Pashinyan has arrived in...,2025-06-20,2025-06-20

## Analysis part

In [78]:
from openai import OpenAI
import time
import os

In [79]:
from dotenv import load_dotenv # you'll want this if you're running on your laptop

In [ ]:
client = OpenAI(api_key="OPENAI_API_KEY")

In [82]:
# summaries for text column


# Initialize OpenAI client
# Load new dataset
# df = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/scraped_data_en.csv")

# Function to classify drug ads
def classify(text):
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Provide 2 sentence summary about the visit."
                    )
                },
                {
                    "role": "user",
                    "content": text
                }
            ],
            temperature=0.0,
            max_tokens=20,
            top_p=1
        )
        return response.choices[0].text.content.strip().lower()
    except Exception as e:
        print(f"Error with message: {text[:50]}... — {e}")
        return "error"

# Apply the classifier to each message
df["summary"] = df["text"].apply(lambda msg: classify(str(msg)))

# Save the results to a new CSV
output_path = "/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_02/data_with_summaries"
df.to_csv(output_path, index=False)

Error with message: Nikol Pashinyan arrived in the Altai Republic of t... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Pari... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Brus... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister Nikol Pashinyan has arrived in the... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister Nikol Pashinyan has arrived in Tür... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in the ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister Nikol Pashinyan has left for Alban... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in the ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister of the Republic of Armenia Nikol Pa... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister Nikol Pashinyan has arrived in Geo... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Muni... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Pari... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister of the Republic of Armenia Nikol P... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan and his wife Anna H... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in the ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan and his wife Anna H... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Holy... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Hungary ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan left for the Russia... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Russ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived on a workin... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan participated in the... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Georgia ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Isla... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Unit... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan, who is in Berlin o... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Isla... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Armenian Prime Minister Nikol Pashinyan, who is on... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Russ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan had a meeting with ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Within the framework of the inaugural Nuclear Ener... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Arab... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Gree... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan left for France on ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan and his wife Anna H... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Repu... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Georgia ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Russ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Fren... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Georgia ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan had a meeting with ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan participated in the... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message:  Prime Minister Nikol Pashinyan had a meeting with... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in Geor... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan has arrived in the ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Turkey o... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Chișinău... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan, together with his ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan participated in the... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan had an informal mee... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Moscow o... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan, together with his ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Fede... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan, who is in Munich o... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in Kazakhst... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Russ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan participated in the... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan, together with his ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan paid a short workin... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: The meeting of the Prime Minister of the Republic ... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: Prime Minister Nikol Pashinyan arrived in the Repu... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Error with message: On October 7, Prime Minister Nikol Pashinyan arriv... — Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A*******LEDE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}