# Analyzing air quality data

### Today, we're working with EPA air pollution data.
We'll look at daily SO2 measurements in 2024.<br>
Data source: https://aqs.epa.gov/aqsweb/airdata/download_files.html<br>
Data description: https://aqs.epa.gov/aqsweb/airdata/FileFormats.html#_daily_summary_files

### We'll analyze SO2 data in 2024
SO2, or sulfur dioxide, is emitted from burning fossil fuels. It's most commonly emitted by power plants, ships, trucks, and volcanoes.

#### There are three federal primary standards for sulfur dioxide (SO2) - 
#### a 1-hour standard of <b>75 parts per billion (ppb)</b>, 
#### a 24-hour standard of <b>0.14 parts per million (ppm)</b>, 
#### and an <b>annual average standard of 0.030 ppm.</b>

In [28]:
import pandas as pd
pd.options.display.max_columns = 50

In [29]:
daily_so2 = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/Veronica's classes/Lesson_3_07-22-working-with-sensor-data/EPA_data/daily_so2_2024.csv")

/var/folders/8_/g6dfnl_n0hd1f_8crnxjdkw00000gn/T/ipykernel_59449/2712561262.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  daily_so2 = pd.read_csv("/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/Veronica's classes/Lesson_3_07-22-working-with-sensor-data/EPA_data/daily_so2_2024.csv")

In [30]:
daily_so2.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,97,3,42401,1,30.770181,-88.087761,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-01,Parts per billion,NaN,23,96.0,0.191304,1.0,10,1.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,CHICKASAW,"Iroquois and Azalea, CHICKASAW, MOBILE CO., A...",Alabama,Mobile,Chickasaw,"Mobile, AL",2024-10-31
1,1,97,3,42401,1,30.770181,-88.087761,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-02,Parts per billion,NaN,23,96.0,1.943478,7.7,8,10.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,CHICKASAW,"Iroquois and Azalea, CHICKASAW, MOBILE CO., A...",Alabama,Mobile,Chickasaw,"Mobile, AL",2024-10-31
2,1,97,3,42401,1,30.770181,-88.087761,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-03,Parts per billion,NaN,23,96.0,0.304348,1.9,16,1.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,CHICKASAW,"Iroquois and Azalea, CHICKASAW, MOBILE CO., A...",Alabama,Mobile,Chickasaw,"Mobile, AL",2024-10-31
3,1,97,3,42401,1,30.770181,-88.087761,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-04,Parts per billion,NaN,23,96.0,1.217391,5.4,12,7.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,CHICKASAW,"Iroquois and Azalea, CHICKASAW, MOBILE CO., A...",Alabama,Mobile,Chickasaw,"Mobile, AL",2024-10-31
4,1,97,3,42401,1,30.770181,-88.087761,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-05,Parts per billion,NaN,23,96.0,0.178261,0.7,10,0.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,CHICKASAW,"Iroquois and Azalea, CHICKASAW, MOBILE CO., A...",Alabama,Mobile,Chickasaw,"Mobile, AL",2024-10-31

In [31]:
daily_so2['Units of Measure'].unique()

array(['Parts per billion'], dtype=object)

In [32]:
daily_so2.shape

(159622, 29)

In [33]:

identifying_features = ['State Code', 'County Code', 'Site Num', 'Latitude', 'Longitude']
daily_violations = daily_so2[daily_so2['Arithmetic Mean'] > .14].groupby(identifying_features)['Arithmetic Mean'].count().reset_index()
daily_violations

     State Code  County Code  Site Num   Latitude   Longitude  Arithmetic Mean
0             1           97         3  30.770181  -88.087761              221
1             1          117      9001  33.092800  -86.807200              424
2             1          119         3  32.362606  -88.277992              250
3             2           90        34  64.845690 -147.727413              332
4             2           90        35  64.762641 -147.310279              342
..          ...          ...       ...        ...         ...              ...
375          56           37        28  41.593611 -109.711150              217
376          56           37       300  41.750556 -109.788333              364
377          56           45       800  43.845390 -104.205120              299
378          72           21        10  18.420089  -66.150615              253
379          72          123         4  17.968352  -66.261365              366

[380 rows x 6 columns]

In [39]:
daily_so2[(daily_so2['State Code'] == 1)
& (daily_so2['County Code'] == 117)
& (daily_so2['Site Num'] == 9001)
& (daily_so2['Date Local'] == '2024-01-01')]

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
424,1,117,9001,42401,1,33.0928,-86.8072,NAD83,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,2024-01-01,Parts per billion,NaN,24,100.0,0.491667,1.6,18,1.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,"Lhoist, Montevallo Plant",7444 State Hwy 25,Alabama,Shelby,Calera,"Birmingham-Hoover, AL",2024-10-31
637,1,117,9001,42401,1,33.0928,-86.8072,NAD83,Sulfur dioxide,3-HR BLK AVG,SO2 3-hour 1971,2024-01-01,Parts per billion,NaN,8,100.0,0.450000,0.8,20,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,"Lhoist, Montevallo Plant",7444 State Hwy 25,Alabama,Shelby,Calera,"Birmingham-Hoover, AL",2024-10-31

In [47]:
daily_violations

     State Code  County Code  Site Num   Latitude   Longitude  Arithmetic Mean
0             1           97         3  30.770181  -88.087761              221
1             1          117      9001  33.092800  -86.807200              424
2             1          119         3  32.362606  -88.277992              250
3             2           90        34  64.845690 -147.727413              332
4             2           90        35  64.762641 -147.310279              342
..          ...          ...       ...        ...         ...              ...
375          56           37        28  41.593611 -109.711150              217
376          56           37       300  41.750556 -109.788333              364
377          56           45       800  43.845390 -104.205120              299
378          72           21        10  18.420089  -66.150615              253
379          72          123         4  17.968352  -66.261365              366

[380 rows x 6 columns]

In [ ]:
daily_so2['C']