In [2]:
import pandas as pd

In [194]:
# openning file with data
df = pd.read_csv('/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_01/archive_data.csv', index_col=False)
df.head()

,link,video_link,title,time,date
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025"
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025"
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025"
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025"
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025"

In [195]:
# cleaning the date column, removing armenian abbreviations and converting to the date format


# armenian month abbreviations to month numbers
armenian_months = {
    'Հնվ': '01', 'Փտր': '02', 'Մար': '03', 'Ապր': '04', 'Մայ': '05', 'Հնս': '06',
    'Հլս': '07', 'Օգս': '08', 'Սեպ': '09', 'Հոկ': '10', 'Նմբ': '11', 'Դեկ': '12'
}

# Split and map months
df['day'] = df['date'].str.extract(r'(\d{2})')
df['arm_month'] = df['date'].str.extract(r'(\w{3})')
df['year'] = df['date'].str.extract(r'(\d{4})')

df['month'] = df['arm_month'].map(armenian_months)

# Combine into ISO format date
df['iso_date'] = pd.to_datetime(df['year'] + '-' + df['month'] + '-' + df['day'])

print(df[['date', 'iso_date']])

              date   iso_date
0     03 Հլս, 2025 2025-07-03
1     02 Հլս, 2025 2025-07-02
2     01 Հլս, 2025 2025-07-01
3     30 Հնս, 2025 2025-06-30
4     27 Հնս, 2025 2025-06-27
...            ...        ...
1270  06 Փտր, 2020 2020-02-06
1271  05 Փտր, 2020 2020-02-05
1272  04 Փտր, 2020 2020-02-04
1273  03 Փտր, 2020 2020-02-03
1274  12 Հոկ, 2021 2021-10-12

[1275 rows x 2 columns]

In [196]:
df

,link,video_link,title,time,date,day,arm_month,year,month,iso_date
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025",03,Հլս,2025,07,2025-07-03
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025",02,Հլս,2025,07,2025-07-02
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025",01,Հլս,2025,07,2025-07-01
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025",30,Հնս,2025,06,2025-06-30
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025",27,Հնս,2025,06,2025-06-27
...,...,...,...,...,...,...,...,...,...,...
1270,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/6g5sFkYDopo?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Կարեն Անդրեա...,19:30,"06 Փտր, 2020",06,Փտր,2020,02,2020-02-06
1271,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/g_N7y10q5jE?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Էդմոն Մարուքյան,19:30,"05 Փտր, 2020",05,Փտր,2020,02,2020-02-05
1272,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/PLfaKqneN8g?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Տիգրան Խաչատ...,19:30,"04 Փտր, 2020",04,Փտր,2020,02,2020-02-04
1273,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/XA3jcUzjQRI?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Ռուբեն Ռուբի...,19:30,"03 Փտր, 2020",03,Փտր,2020,02,2020-02-03
1274,https://www.1tv.am/hy/video/Հարցազրույց-Արսեն-...,https://www.youtube.com/embed/Mo-CuhQ4wNg?auto...,Հարցազրույց Արսեն Թորոսյանի հետ,18:24,"12 Հոկ, 2021",12,Հոկ,2021,10,2021-10-12

In [197]:
# creating new 'cleaned_title' column where we are cleaning names to keep only the name of the guest

df['cleaned_title'] = (
    df['title']
    .str.replace(
        r'Հարցազրույց Պետրոս Ղազարյանի հետ.|Հարցազրույց|հետ|Պետրոս Ղազարյանի հարցազրույցը|ՀՀ Ազգային ժողովի նախագահ|ՀՀ վարչապետ|փոխվարչապետ',
        '',
        regex=True
    )
    .str.replace(r'ի\b', '', regex=True)
    .str.lower()
    .str.strip()
)

In [ ]:
df.to_csv("cleaned_archive_data.csv", index=False)

### This cleaned_archive_data.csv file was opened in youtube_api.ipynb notebook. Then processed, Duration, Thumbnail_URL, Views were added to the data. I also cut data, keeping the period from June 20

In [3]:
df = pd.read_csv('/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_01/data_to_analyze_2021-2025.csv', index_col=False)
df.head()

,link,video_link,title,time,date,day,arm_month,year,month,iso_date,cleaned_title,video_id,Duration,Thumbnail_URL,Views
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025",3,Հլս,2025,7,2025-07-03,սոս թաթիկյան,gkLMht3Vt-k,00:35:21,https://i.ytimg.com/vi/gkLMht3Vt-k/hqdefault.jpg,34201.0
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025",2,Հլս,2025,7,2025-07-02,համբիկ սարաֆյան,yjj8ISwxTwE,00:28:10,https://i.ytimg.com/vi/yjj8ISwxTwE/hqdefault.jpg,34252.0
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025",1,Հլս,2025,7,2025-07-01,կայա կալաս,Hd6l_IRhygI,00:13:05,https://i.ytimg.com/vi/Hd6l_IRhygI/hqdefault.jpg,42904.0
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025",30,Հնս,2025,6,2025-06-30,արթուր պողոսյան,d5x7uI6cCLI,00:36:36,https://i.ytimg.com/vi/d5x7uI6cCLI/hqdefault.jpg,99204.0
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025",27,Հնս,2025,6,2025-06-27,էլեն հոխիկյան,gpIDqXFZx8o,00:20:50,https://i.ytimg.com/vi/gpIDqXFZx8o/hqdefault.jpg,42113.0

In [4]:
df['cleaned_title'].value_counts()

cleaned_title
անդրանիկ քոչարյան     23
վահագն ալեքսանյան     23
արամ սարգսյան         22
հայկ կոնջորյան        22
էդմոն մարուքյան       22
                      ..
մար գրիգորյան          1
շիլա փայլան            1
նժդեհ հովսեփյան        1
ալեն բերսե             1
արմեն հովհաննիսյան     1
Name: count, Length: 356, dtype: int64

In [5]:
guests = df.pivot_table(
    index='cleaned_title',   # people as rows
    columns='year',          # years as columns
    values='link',           # any column with data to count
    aggfunc='count',         # count how many times each person appears per year
    fill_value=0             # fill missing combinations with 0
)

In [6]:
guests = guests.assign(Total=guests.sum(axis=1)).sort_values('Total', ascending=False)

In [7]:
guests

year                         2021  2022  2023  2024  2025  Total
cleaned_title
անդրանիկ քոչարյան               4     4     6     6     3     23
վահագն ալեքսանյան               1     4     5     9     4     23
էդմոն մարուքյան                 4    12     6     0     0     22
հայկ կոնջորյան                  2     8     4     3     5     22
արամ սարգսյան                   3     6     6     5     2     22
...                           ...   ...   ...   ...   ...    ...
լևոն տեր-պետրոսյան              0     1     0     0     0      1
խորեն վարդապետ հովհաննիսյան     0     0     0     0     1      1
ծովինար վարդանյան               0     0     1     0     0      1
կայա կալաս                      0     0     0     0     1      1
ֆրենկ փալոուն                   0     1     0     0     0      1

[356 rows x 6 columns]

In [1]:
df[(df['year'] == "2023") & (df["cleaned_title"] == "Էդմոն Մարուքյան")]

NameError: name 'df' is not defined