In [ ]:
pip install google-api-python-client

Collecting google-api-python-client
  Downloading google_api_python_client-2.176.0-py3-none-any.whl.metadata (7.0 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.40.3-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.25.1-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.70.0-py3-none-any.whl.metadata (9.3 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Using cached protobuf-6.31.1-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.3)
Collecting cachetools<6.0,>=2.0.0 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2024.8.30)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Using cached pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Downloading google_api_python_client-2.176.0-py3-none-any.whl (13.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 16.1 MB/s eta 0:00:00a 0:00:01
Downloading google_api_core-2.25.1-py3-none-any.whl (160 kB)
Downloading google_auth-2.40.3-py2.py3-none-any.whl (216 kB)
Downloading cachetools-5.5.2-py3-none-any.whl (10 kB)
Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Downloading googleapis_common_protos-1.70.0-py3-none-any.whl (294 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
Using cached protobuf-6.31.1-cp39-abi3-macosx_10_9_universal2.whl (425 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Using cached pyasn1-0.6.1-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Installing collected packages: uritemplate, pyasn1, protobuf, httplib2, cachetools, rsa, pyasn1-modules, proto-plus, googleapis-common-protos, google-auth, google-auth-httplib2, google-api-core, google-api-python-client
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [google-api-python-client]api-python-client]
Successfully installed cachetools-5.5.2 google-api-core-2.25.1 google-api-python-client-2.176.0 google-auth-2.40.3 google-auth-httplib2-0.2.0 googleapis-common-protos-1.70.0 httplib2-0.22.0 proto-plus-1.26.1 protobuf-6.31.1 pyasn1-0.6.1 pyasn1-modules-0.4.2 rsa-4.9.1 uritemplate-4.2.0
Note: you may need to restart the kernel to use updated packages.

In [20]:
import re
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import pandas as pd

from dotenv import load_dotenv
import os

In [21]:
# openning file with data
df = pd.read_csv('/Users/katemamyan/Documents/GitHub/LEDE_PROGRAM/project_01/archive_data.csv', index_col=False)
df.head()

,link,video_link,title,time,date
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025"
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025"
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025"
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025"
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025"

In [7]:
load_dotenv(override=True)
api_key = os.environ['API_KEY']

In [10]:
def get_video_id(youtube_link):
    """Extracts the video ID from a YouTube URL."""
    # Regex to match various YouTube URL formats
    # Handles watch?v=, youtu.be/, embed/, and shorts/
    match = re.search(r"(?:v=|youtu\.be/|embed/|shorts/)([\w-]{11})", youtube_link)
    if match:
        return match.group(1)
    return None

In [13]:
def get_video_stats(video_ids, api_key):
    """
    Fetches statistics (views, likes, comments, shares) for a list of YouTube video IDs.
    """
    youtube = build("youtube", "v3", developerKey=api_key)
    stats_data = {}

    # The API allows up to 50 video IDs per request
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        try:
            request = youtube.videos().list(
                part="statistics",
                id=",".join(batch_ids)
            )
            response = request.execute()

            for item in response.get("items", []):
                video_id = item["id"]
                statistics = item.get("statistics", {})
                stats_data[video_id] = {
                    "views": statistics.get("viewCount", "N/A"),
                    "likes": statistics.get("likeCount", "N/A"),
                    "comments": statistics.get("commentCount", "N/A"),
                    # Shares are not directly exposed as a discrete count in the API for individual videos
                    # You might infer sharing activity from public comments or external tracking if needed
                    "shares": "N/A (Not directly available via API for individual videos)"
                }
        except HttpError as e:
            print(f"An HTTP error {e.resp.status} occurred: {e.content}")
        except Exception as e:
            print(f"An error occurred: {e}")
    return stats_data

if __name__ == "__main__":
    youtube_links = df['video_link']

    video_ids = []
    for link in youtube_links:
        vid_id = get_video_id(link)
        if vid_id:
            video_ids.append(vid_id)
        else:
            print(f"Could not extract video ID from: {link}")

    if video_ids:
        all_video_stats = get_video_stats(video_ids, api_key)

        for link in youtube_links:
            vid_id = get_video_id(link)
            if vid_id and vid_id in all_video_stats:
                stats = all_video_stats[vid_id]
                print(f"\n--- Stats for: {link} (ID: {vid_id}) ---")
                print(f"  Views: {stats['views']}")
                print(f"  Likes: {stats['likes']}")
                print(f"  Comments: {stats['comments']}")
                print(f"  Shares: {stats['shares']}") # Note: Shares often 'N/A'
            elif vid_id:
                print(f"\n--- No stats found for: {link} (ID: {vid_id}). Might be private, deleted, or incorrect ID. ---")
            else:
                print(f"\n--- Skipping link: {link} (Invalid or unextractable ID) ---")
    else:
        print("No valid video IDs found in the provided list.")

Could not extract video ID from: https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flurer1tv%2Fvideos%2F1285800781771444%2F&show_text=0&width=560&autoplay=1
Could not extract video ID from: https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flurer.1tv%2Fvideos%2F322899835336041%2F&show_text=0&width=560&autoplay=1
Could not extract video ID from: https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Flurer.1tv%2Fvideos%2F501143377462564%2F&show_text=0&width=560&autoplay=1

--- Stats for: https://www.youtube.com/embed/gkLMht3Vt-k?autoplay=1&autohide=1 (ID: gkLMht3Vt-k) ---
  Views: 33761
  Likes: 410
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/yjj8ISwxTwE?autoplay=1&autohide=1 (ID: yjj8ISwxTwE) ---
  Views: 33991
  Likes: 518
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/Hd6l_IRhygI?autoplay=1&autohide=1 (ID: Hd6l_IRhygI) ---
  Views: 42727
  Likes: 888
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/d5x7uI6cCLI?autoplay=1&autohide=1 (ID: d5x7uI6cCLI) ---
  Views: 97758
  Likes: 1384
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/gpIDqXFZx8o?autoplay=1&autohide=1 (ID: gpIDqXFZx8o) ---
  Views: 42014
  Likes: 504
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/L9QYke6Lavg?autoplay=1&autohide=1 (ID: L9QYke6Lavg) ---
  Views: 145988
  Likes: 3177
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/YQ3IWIXioi8?autoplay=1&autohide=1 (ID: YQ3IWIXioi8) ---
  Views: 100581
  Likes: 1183
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/g9xybkHV0lc?autoplay=1&autohide=1 (ID: g9xybkHV0lc) ---
  Views: 118191
  Likes: 1829
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/eVYSKBkEQ3c?autoplay=1&autohide=1 (ID: eVYSKBkEQ3c) ---
  Views: 45451
  Likes: 255
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/9J1L57KDjh0?autoplay=1&autohide=1 (ID: 9J1L57KDjh0) ---
  Views: 36008
  Likes: 262
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/lgK9ftDnw7k?autoplay=1&autohide=1 (ID: lgK9ftDnw7k) ---
  Views: 30620
  Likes: 231
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/TpKNCQw712I?autoplay=1&autohide=1 (ID: TpKNCQw712I) ---
  Views: 18956
  Likes: 247
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/gRysYMqznrU?autoplay=1&autohide=1 (ID: gRysYMqznrU) ---
  Views: 69733
  Likes: 922
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/6hiWBZOxhhE?autoplay=1&autohide=1 (ID: 6hiWBZOxhhE) ---
  Views: 34007
  Likes: 357
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/VaOALzBUEpY?autoplay=1&autohide=1 (ID: VaOALzBUEpY) ---
  Views: 24478
  Likes: 202
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/b264_CxWxSg?autoplay=1&autohide=1 (ID: b264_CxWxSg) ---
  Views: 93460
  Likes: 761
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/vCbnIJM8ihQ?autoplay=1&autohide=1 (ID: vCbnIJM8ihQ) ---
  Views: 91580
  Likes: 502
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/m_DdC-tuJNc?autoplay=1&autohide=1 (ID: m_DdC-tuJNc) ---
  Views: 21387
  Likes: 303
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/WBVw2zOFiRM?autoplay=1&autohide=1 (ID: WBVw2zOFiRM) ---
  Views: 32174
  Likes: 608
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/lXqEuNcSoB4?autoplay=1&autohide=1 (ID: lXqEuNcSoB4) ---
  Views: 73305
  Likes: 1157
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/I8XW7f98sKI?autoplay=1&autohide=1 (ID: I8XW7f98sKI) ---
  Views: 23749
  Likes: 415
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/bR85x0q5nSI?autoplay=1&autohide=1 (ID: bR85x0q5nSI) ---
  Views: 36403
  Likes: 705
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/dD8PMpjziew?autoplay=1&autohide=1 (ID: dD8PMpjziew) ---
  Views: 20328
  Likes: 172
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/0WyNm0kfdkg?autoplay=1&autohide=1 (ID: 0WyNm0kfdkg) ---
  Views: 4800
  Likes: 52
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- No stats found for: https://www.youtube.com/embed/QzlgWDC63qE?autoplay=1&autohide=1 (ID: QzlgWDC63qE). Might be private, deleted, or incorrect ID. ---

--- Stats for: https://www.youtube.com/embed/IQ9Ghx8vWHQ?autoplay=1&autohide=1 (ID: IQ9Ghx8vWHQ) ---
  Views: 51710
  Likes: 794
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/ZoxxSL1qUps?autoplay=1&autohide=1 (ID: ZoxxSL1qUps) ---
  Views: 76744
  Likes: 1143
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/9aeOF-4ZWf0?autoplay=1&autohide=1 (ID: 9aeOF-4ZWf0) ---
  Views: 19430
  Likes: 191
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/1hIJrTDufbE?autoplay=1&autohide=1 (ID: 1hIJrTDufbE) ---
  Views: 77732
  Likes: 1193
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/WsJQYLxGo9I?autoplay=1&autohide=1 (ID: WsJQYLxGo9I) ---
  Views: 26463
  Likes: 248
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/XUc3kLWgZQg?autoplay=1&autohide=1 (ID: XUc3kLWgZQg) ---
  Views: 65938
  Likes: 1001
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/NLFYH-I985g?autoplay=1&autohide=1 (ID: NLFYH-I985g) ---
  Views: 108402
  Likes: 1713
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/9KDAEGmyy-4?autoplay=1&autohide=1 (ID: 9KDAEGmyy-4) ---
  Views: 81455
  Likes: 909
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/kwPt9TXlRgk?autoplay=1&autohide=1 (ID: kwPt9TXlRgk) ---
  Views: 49654
  Likes: 253
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/6LnkR5jb46k?autoplay=1&autohide=1 (ID: 6LnkR5jb46k) ---
  Views: 12936
  Likes: 121
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/rR4w1tKb1M0?autoplay=1&autohide=1 (ID: rR4w1tKb1M0) ---
  Views: 20309
  Likes: 151
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/i13ZLwYoLnE?autoplay=1&autohide=1 (ID: i13ZLwYoLnE) ---
  Views: 30441
  Likes: 214
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/wZPqzqnfylg?autoplay=1&autohide=1 (ID: wZPqzqnfylg) ---
  Views: 51815
  Likes: 955
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/plzW6EQKlYQ?autoplay=1&autohide=1 (ID: plzW6EQKlYQ) ---
  Views: 43166
  Likes: 640
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/hcLhnUIN7Y0?autoplay=1&autohide=1 (ID: hcLhnUIN7Y0) ---
  Views: 23224
  Likes: 216
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/lqmSDYB-_hY?autoplay=1&autohide=1 (ID: lqmSDYB-_hY) ---
  Views: 26974
  Likes: 344
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/62_pUJLnvlo?autoplay=1&autohide=1 (ID: 62_pUJLnvlo) ---
  Views: 28124
  Likes: 548
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/tbQATYApYSI?autoplay=1&autohide=1 (ID: tbQATYApYSI) ---
  Views: 21643
  Likes: 239
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/kJLWgZQ-myI?autoplay=1&autohide=1 (ID: kJLWgZQ-myI) ---
  Views: 82240
  Likes: 547
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/330z2yi8DG0?autoplay=1&autohide=1 (ID: 330z2yi8DG0) ---
  Views: 10713
  Likes: 69
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/yGrd3FBdix8?autoplay=1&autohide=1 (ID: yGrd3FBdix8) ---
  Views: 32613
  Likes: 314
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/11H4Oqi5jXU?autoplay=1&autohide=1 (ID: 11H4Oqi5jXU) ---
  Views: 56385
  Likes: 962
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/s8z730bpo2Y?autoplay=1&autohide=1 (ID: s8z730bpo2Y) ---
  Views: 54518
  Likes: 534
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/nCr1QheWiAQ?autoplay=1&autohide=1 (ID: nCr1QheWiAQ) ---
  Views: 44339
  Likes: 308
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/joSP83VHA3I?autoplay=1&autohide=1 (ID: joSP83VHA3I) ---
  Views: 46011
  Likes: 782
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/T4wlpkrrpTM?autoplay=1&autohide=1 (ID: T4wlpkrrpTM) ---
  Views: 40687
  Likes: 481
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/8HStP0XZ5zQ?autoplay=1&autohide=1 (ID: 8HStP0XZ5zQ) ---
  Views: 18852
  Likes: 190
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/DEqd9AROqe4?autoplay=1&autohide=1 (ID: DEqd9AROqe4) ---
  Views: 78110
  Likes: 980
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/ciTvwcUaanE?autoplay=1&autohide=1 (ID: ciTvwcUaanE) ---
  Views: 24651
  Likes: 184
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/W4U6OGE1Sdk?autoplay=1&autohide=1 (ID: W4U6OGE1Sdk) ---
  Views: 55846
  Likes: 647
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/XQUhqQOUACE?autoplay=1&autohide=1 (ID: XQUhqQOUACE) ---
  Views: 62063
  Likes: 956
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/34FcpDxd3nY?autoplay=1&autohide=1 (ID: 34FcpDxd3nY) ---
  Views: 51201
  Likes: 813
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/AkJy5NJ5ds4?autoplay=1&autohide=1 (ID: AkJy5NJ5ds4) ---
  Views: 27689
  Likes: 548
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/qOem8WMgRqI?autoplay=1&autohide=1 (ID: qOem8WMgRqI) ---
  Views: 30924
  Likes: 140
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/7utSMb_5Dkw?autoplay=1&autohide=1 (ID: 7utSMb_5Dkw) ---
  Views: 31359
  Likes: 742
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/JHPaKoFH3Ec?autoplay=1&autohide=1 (ID: JHPaKoFH3Ec) ---
  Views: 9937
  Likes: 44
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/foNM1cFHOTo?autoplay=1&autohide=1 (ID: foNM1cFHOTo) ---
  Views: 129281
  Likes: 961
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/QXe6voYx9r4?autoplay=1&autohide=1 (ID: QXe6voYx9r4) ---
  Views: 14144
  Likes: 77
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/NqmM11ROeBw?autoplay=1&autohide=1 (ID: NqmM11ROeBw) ---
  Views: 35211
  Likes: 302
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/xqMrtijccuM?autoplay=1&autohide=1 (ID: xqMrtijccuM) ---
  Views: 48686
  Likes: 911
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/2f2bBulNidU?autoplay=1&autohide=1 (ID: 2f2bBulNidU) ---
  Views: 42694
  Likes: 260
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/HaOw3W2h5Yg?autoplay=1&autohide=1 (ID: HaOw3W2h5Yg) ---
  Views: 48161
  Likes: 795
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/JWmKXMjNULo?autoplay=1&autohide=1 (ID: JWmKXMjNULo) ---
  Views: 24107
  Likes: 301
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/EtbizvjWz5A?autoplay=1&autohide=1 (ID: EtbizvjWz5A) ---
  Views: 43975
  Likes: 665
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/MT9t2a7a3j8?autoplay=1&autohide=1 (ID: MT9t2a7a3j8) ---
  Views: 176650
  Likes: 3401
  Comments: 565
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/vKDlqqbhRuU?autoplay=1&autohide=1 (ID: vKDlqqbhRuU) ---
  Views: 12319
  Likes: 86
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/SPhG9lFMvZg?autoplay=1&autohide=1 (ID: SPhG9lFMvZg) ---
  Views: 11047
  Likes: 149
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/VP-3f82wC6o?autoplay=1&autohide=1 (ID: VP-3f82wC6o) ---
  Views: 39864
  Likes: 647
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/oKH47mw0Zpw?autoplay=1&autohide=1 (ID: oKH47mw0Zpw) ---
  Views: 12734
  Likes: 94
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/iA6jfsTpWkc?autoplay=1&autohide=1 (ID: iA6jfsTpWkc) ---
  Views: 22633
  Likes: 122
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/fDJUutoThxo?autoplay=1&autohide=1 (ID: fDJUutoThxo) ---
  Views: 14687
  Likes: 180
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/KubiymERfVA?autoplay=1&autohide=1 (ID: KubiymERfVA) ---
  Views: 34001
  Likes: 608
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/g6BXBertBbg?si=D4rdLo9ti5KLCDb9?autoplay=1&autohide=1 (ID: g6BXBertBbg) ---
  Views: 44852
  Likes: 710
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/-ocRwHq4qqM?autoplay=1&autohide=1 (ID: -ocRwHq4qqM) ---
  Views: 39526
  Likes: 742
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/azYrbMmjW9Y?autoplay=1&autohide=1 (ID: azYrbMmjW9Y) ---
  Views: 46006
  Likes: 1143
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/mFd1WNIQXg0?autoplay=1&autohide=1 (ID: mFd1WNIQXg0) ---
  Views: 5703
  Likes: 51
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/sO-HjfA2B3M?autoplay=1&autohide=1 (ID: sO-HjfA2B3M) ---
  Views: 21012
  Likes: 305
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/wMpMHwlRaIw?autoplay=1&autohide=1 (ID: wMpMHwlRaIw) ---
  Views: 17082
  Likes: 223
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/rCEb9pU7Rko?autoplay=1&autohide=1 (ID: rCEb9pU7Rko) ---
  Views: 37336
  Likes: 899
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/9QovpP63kGY?autoplay=1&autohide=1 (ID: 9QovpP63kGY) ---
  Views: 14530
  Likes: 169
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/2beBtQAXlbo?autoplay=1&autohide=1 (ID: 2beBtQAXlbo) ---
  Views: 56259
  Likes: 405
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/CigKPH_vhLo?autoplay=1&autohide=1 (ID: CigKPH_vhLo) ---
  Views: 27852
  Likes: 417
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/0FKCAATFOJc?autoplay=1&autohide=1 (ID: 0FKCAATFOJc) ---
  Views: 39886
  Likes: 763
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/VmE3cOfaLxk?autoplay=1&autohide=1 (ID: VmE3cOfaLxk) ---
  Views: 40334
  Likes: 462
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/2Nk4_8inWsE?autoplay=1&autohide=1 (ID: 2Nk4_8inWsE) ---
  Views: 53954
  Likes: 693
  Comments: N/A
  Shares: N/A (Not directly available via API for individual videos)

--- Stats for: https://www.youtube.com/embed/FXXijvwGagk?autoplay=1&autohide=1 (ID: FXXijvwGagk) ---
  Views: 30231

In [17]:
all_video_stats

{'gkLMht3Vt-k': {'views': '33761',
  'likes': '410',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'yjj8ISwxTwE': {'views': '33991',
  'likes': '518',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'Hd6l_IRhygI': {'views': '42727',
  'likes': '888',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'd5x7uI6cCLI': {'views': '97758',
  'likes': '1384',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'gpIDqXFZx8o': {'views': '42014',
  'likes': '504',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'L9QYke6Lavg': {'views': '145988',
  'likes': '3177',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'YQ3IWIXioi8': {'views': '100581',
  'likes': '1183',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'g9xybkHV0lc': {'views': '118191',
  'likes': '1829',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'eVYSKBkEQ3c': {'views': '45451',
  'likes': '255',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '9J1L57KDjh0': {'views': '36008',
  'likes': '262',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'lgK9ftDnw7k': {'views': '30620',
  'likes': '231',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'TpKNCQw712I': {'views': '18956',
  'likes': '247',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'gRysYMqznrU': {'views': '69733',
  'likes': '922',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '6hiWBZOxhhE': {'views': '34007',
  'likes': '357',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'VaOALzBUEpY': {'views': '24478',
  'likes': '202',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'b264_CxWxSg': {'views': '93460',
  'likes': '761',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'vCbnIJM8ihQ': {'views': '91580',
  'likes': '502',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'm_DdC-tuJNc': {'views': '21387',
  'likes': '303',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'WBVw2zOFiRM': {'views': '32174',
  'likes': '608',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'lXqEuNcSoB4': {'views': '73305',
  'likes': '1157',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'I8XW7f98sKI': {'views': '23749',
  'likes': '415',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'bR85x0q5nSI': {'views': '36403',
  'likes': '705',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'dD8PMpjziew': {'views': '20328',
  'likes': '172',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '0WyNm0kfdkg': {'views': '4800',
  'likes': '52',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'IQ9Ghx8vWHQ': {'views': '51710',
  'likes': '794',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'ZoxxSL1qUps': {'views': '76744',
  'likes': '1143',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '9aeOF-4ZWf0': {'views': '19430',
  'likes': '191',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '1hIJrTDufbE': {'views': '77732',
  'likes': '1193',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'WsJQYLxGo9I': {'views': '26463',
  'likes': '248',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'XUc3kLWgZQg': {'views': '65938',
  'likes': '1001',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'NLFYH-I985g': {'views': '108402',
  'likes': '1713',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '9KDAEGmyy-4': {'views': '81455',
  'likes': '909',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'kwPt9TXlRgk': {'views': '49654',
  'likes': '253',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '6LnkR5jb46k': {'views': '12936',
  'likes': '121',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'rR4w1tKb1M0': {'views': '20309',
  'likes': '151',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'i13ZLwYoLnE': {'views': '30441',
  'likes': '214',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'wZPqzqnfylg': {'views': '51815',
  'likes': '955',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'plzW6EQKlYQ': {'views': '43166',
  'likes': '640',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'hcLhnUIN7Y0': {'views': '23224',
  'likes': '216',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'lqmSDYB-_hY': {'views': '26974',
  'likes': '344',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '62_pUJLnvlo': {'views': '28124',
  'likes': '548',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'tbQATYApYSI': {'views': '21643',
  'likes': '239',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'kJLWgZQ-myI': {'views': '82240',
  'likes': '547',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '330z2yi8DG0': {'views': '10713',
  'likes': '69',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'yGrd3FBdix8': {'views': '32613',
  'likes': '314',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '11H4Oqi5jXU': {'views': '56385',
  'likes': '962',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 's8z730bpo2Y': {'views': '54518',
  'likes': '534',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'nCr1QheWiAQ': {'views': '44339',
  'likes': '308',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'joSP83VHA3I': {'views': '46011',
  'likes': '782',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'T4wlpkrrpTM': {'views': '40687',
  'likes': '481',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '8HStP0XZ5zQ': {'views': '18852',
  'likes': '190',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'DEqd9AROqe4': {'views': '78110',
  'likes': '980',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'ciTvwcUaanE': {'views': '24651',
  'likes': '184',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'W4U6OGE1Sdk': {'views': '55846',
  'likes': '647',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'XQUhqQOUACE': {'views': '62063',
  'likes': '956',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '34FcpDxd3nY': {'views': '51201',
  'likes': '813',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'AkJy5NJ5ds4': {'views': '27689',
  'likes': '548',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'qOem8WMgRqI': {'views': '30924',
  'likes': '140',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '7utSMb_5Dkw': {'views': '31359',
  'likes': '742',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'JHPaKoFH3Ec': {'views': '9937',
  'likes': '44',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'foNM1cFHOTo': {'views': '129281',
  'likes': '961',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'QXe6voYx9r4': {'views': '14144',
  'likes': '77',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'NqmM11ROeBw': {'views': '35211',
  'likes': '302',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'xqMrtijccuM': {'views': '48686',
  'likes': '911',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '2f2bBulNidU': {'views': '42694',
  'likes': '260',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'HaOw3W2h5Yg': {'views': '48161',
  'likes': '795',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'JWmKXMjNULo': {'views': '24107',
  'likes': '301',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'EtbizvjWz5A': {'views': '43975',
  'likes': '665',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'MT9t2a7a3j8': {'views': '176650',
  'likes': '3401',
  'comments': '565',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'vKDlqqbhRuU': {'views': '12319',
  'likes': '86',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'SPhG9lFMvZg': {'views': '11047',
  'likes': '149',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'VP-3f82wC6o': {'views': '39864',
  'likes': '647',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'oKH47mw0Zpw': {'views': '12734',
  'likes': '94',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'iA6jfsTpWkc': {'views': '22633',
  'likes': '122',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'fDJUutoThxo': {'views': '14687',
  'likes': '180',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'KubiymERfVA': {'views': '34001',
  'likes': '608',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'g6BXBertBbg': {'views': '44852',
  'likes': '710',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '-ocRwHq4qqM': {'views': '39526',
  'likes': '742',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'azYrbMmjW9Y': {'views': '46006',
  'likes': '1143',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'mFd1WNIQXg0': {'views': '5703',
  'likes': '51',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'sO-HjfA2B3M': {'views': '21012',
  'likes': '305',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'wMpMHwlRaIw': {'views': '17082',
  'likes': '223',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'rCEb9pU7Rko': {'views': '37336',
  'likes': '899',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '9QovpP63kGY': {'views': '14530',
  'likes': '169',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '2beBtQAXlbo': {'views': '56259',
  'likes': '405',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'CigKPH_vhLo': {'views': '27852',
  'likes': '417',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '0FKCAATFOJc': {'views': '39886',
  'likes': '763',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'VmE3cOfaLxk': {'views': '40334',
  'likes': '462',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '2Nk4_8inWsE': {'views': '53954',
  'likes': '693',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'FXXijvwGagk': {'views': '30231',
  'likes': '585',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'olE-AcwQWfc': {'views': '108539',
  'likes': '1525',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '3EZ3YxznGGg': {'views': '17028',
  'likes': '168',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'bDchPif3RP4': {'views': '24064',
  'likes': '355',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'M5Lse4GEyxE': {'views': '13052',
  'likes': '153',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'vlZFyYDeDrU': {'views': '17517',
  'likes': '133',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'N-I33eg13Pc': {'views': '25513',
  'likes': '500',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'wUryATZPzKY': {'views': '32523',
  'likes': '591',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'r4QAYCSbP98': {'views': '50834',
  'likes': '1153',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'fH8UILDdcdo': {'views': '42576',
  'likes': '1114',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'QFAwX1AvYJU': {'views': '16558',
  'likes': '146',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'X2BIon6sok4': {'views': '24171',
  'likes': '324',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'PQivdPGlwj4': {'views': '12754',
  'likes': '101',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'mpPiJlun5eE': {'views': '110689',
  'likes': '1913',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'NjXcxV5sTTw': {'views': '47528',
  'likes': '804',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'pXq9TSDdhyU': {'views': '94285',
  'likes': '1105',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '8PIsv-uAsR4': {'views': '26494',
  'likes': '321',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '7TfNyvzPZWA': {'views': '26048',
  'likes': '438',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'hqF9xPxwaE8': {'views': '4850',
  'likes': '47',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'hCvAVvxN1EE': {'views': '6924',
  'likes': '62',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'b9jI1eztRgA': {'views': '8560',
  'likes': '91',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'ucjRgCU9JCU': {'views': '6379',
  'likes': '64',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'xINTn3NkvbM': {'views': '18611',
  'likes': '182',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'dpIm085pYEQ': {'views': '13065',
  'likes': '124',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'euqOeivpwsE': {'views': '18973',
  'likes': '270',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '7XrUEmCANV8': {'views': '7844',
  'likes': '121',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '0b3NJn2zZvM': {'views': '54094',
  'likes': '754',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'jSrGnqY-n0Q': {'views': '75118',
  'likes': '1251',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'EXWRHTqYNfI': {'views': '11031',
  'likes': '113',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'I7ZsAp58-0s': {'views': '18476',
  'likes': '147',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'qI4O8gruurc': {'views': '18367',
  'likes': '254',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'VNmW-qHcIqU': {'views': '7451',
  'likes': '72',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'q2CaNQc5Z0o': {'views': '8398',
  'likes': '83',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'hRxjIrmN0qY': {'views': '69956',
  'likes': '883',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'AJ6u0V0RpQk': {'views': '71611',
  'likes': '987',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'rW_c8P4O2KI': {'views': '13594',
  'likes': '176',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'Pgb95pBpMeE': {'views': '20390',
  'likes': '202',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '9ANZMW7_sE8': {'views': '30570',
  'likes': '523',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'SqDFUZxVtvM': {'views': '64675',
  'likes': '842',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '6BV4LPvlcpg': {'views': '10600',
  'likes': '106',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'XkJKjJAE998': {'views': '11402',
  'likes': '131',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'HPyFJSQQTe0': {'views': '20636',
  'likes': '214',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 'kfs6q9ic0fc': {'views': '36804',
  'likes': '424',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '4GA3qOLST18': {'views': '29727',
  'likes': '545',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},
 '7Q5KahHABqo': {'views': '11761',
  'likes': '107',
  'comments': 'N/A',
  'shares': 'N/A (Not directly available via API for individual videos)'},

In [28]:


def get_video_id(youtube_link):
    """Extracts the video ID from a YouTube URL."""
    match = re.search(r"(?:v=|youtu\.be/|embed/|shorts/)([\w-]{11})", youtube_link)
    if match:
        return match.group(1)
    return None

def parse_iso8601_duration(iso_duration):
    """
    Parses an ISO 8601 duration string (e.g., 'PT1H2M3S') into total seconds.
    Returns duration in HH:MM:SS format or total seconds.
    """
    try:
        duration_obj = isodate.parse_duration(iso_duration)
        total_seconds = int(duration_obj.total_seconds())

        hours, remainder = divmod(total_seconds, 3600)
        minutes, seconds = divmod(remainder, 60)

        # Return as HH:MM:SS string
        return f"{hours:02}:{minutes:02}:{seconds:02}"
    except Exception:
        return "N/A" # Handle cases where parsing fails

def get_video_stats(video_ids, api_key):
    """
    Fetches statistics (views, likes, comments) for a list of YouTube video IDs.
    Returns a dictionary mapping video_id to its statistics.
    """
    youtube = build("youtube", "v3", developerKey=api_key)
    stats_data = {}

    # The API allows up to 50 video IDs per request
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        try:
            request = youtube.videos().list(
                part="statistics",
                id=",".join(batch_ids)
            )
            response = request.execute()

            for item in response.get("items", []):
                video_id = item["id"]
                statistics = item.get("statistics", {})
                stats_data[video_id] = {
                    "views": int(statistics.get("viewCount", 0)),  # Convert to int, default to 0
                    "likes": int(statistics.get("likeCount", 0)),  # Convert to int, default to 0
                    "comments": int(statistics.get("commentCount", 0)), # Convert to int, default to 0
                    "shares": "N/A" # Still not directly available via API
                    
                }
        except HttpError as e:
            print(f"An HTTP error {e.resp.status} occurred for batch: {batch_ids}. Error: {e.content}")
        except Exception as e:
            print(f"An unexpected error occurred for batch: {batch_ids}. Error: {e}")
    return stats_data

# --- SEPARATE BLOCK FOR DURATION FETCHING ---
def get_video_stats_with_duration(video_ids, api_key):
    """
    Fetches statistics (views, likes, comments) and contentDetails (duration)
    for a list of YouTube video IDs.
    Returns a dictionary mapping video_id to its statistics including duration.
    """
    youtube = build("youtube", "v3", developerKey=api_key)
    stats_data = {}

    # The API allows up to 50 video IDs per request
    for i in range(0, len(video_ids), 50):
        batch_ids = video_ids[i:i+50]
        try:
            request = youtube.videos().list(
                part="statistics,contentDetails", # Requesting both statistics and contentDetails
                id=",".join(batch_ids)
            )
            response = request.execute()

            for item in response.get("items", []):
                video_id = item["id"]
                statistics = item.get("statistics", {})
                content_details = item.get("contentDetails", {}) # Get contentDetails
                
                duration_iso = content_details.get("duration", "N/A")
                duration_formatted = parse_iso8601_duration(duration_iso)

                stats_data[video_id] = {
                    "views": int(statistics.get("viewCount", 0)),
                    "likes": int(statistics.get("likeCount", 0)),
                    "comments": int(statistics.get("commentCount", 0)),
                    "shares": "N/A", # Still not directly available via API
                    "duration": duration_formatted # Add duration
                }
        except HttpError as e:
            print(f"An HTTP error {e.resp.status} occurred for batch: {batch_ids}. Error: {e.content}")
        except Exception as e:
            print(f"An unexpected error occurred for batch: {batch_ids}. Error: {e}")
    return stats_data
# --- END SEPARATE BLOCK ---

if __name__ == "__main__":
    # 1. Extract Video IDs and add as a new column
    df['video_id'] = df['video_link'].apply(get_video_id)

    # Get a list of unique valid video IDs to fetch stats for
    # Filter out None values in case some links didn't yield an ID
    valid_video_ids = [vid for vid in df['video_id'].unique() if vid]

    if valid_video_ids:
        print(f"\n--- Fetching Views, Likes, Comments, AND Duration for {len(valid_video_ids)} unique video IDs ---")
        all_stats_data = get_video_stats_with_duration(valid_video_ids, api_key)

        df_all_stats = df.copy() # Create another copy
        df_all_stats['views'] = df_all_stats['video_id'].map(lambda x: all_stats_data.get(x, {}).get('views', 'N/A'))
        df_all_stats['likes'] = df_all_stats['video_id'].map(lambda x: all_stats_data.get(x, {}).get('likes', 'N/A'))
        df_all_stats['comments'] = df_all_stats['video_id'].map(lambda x: all_stats_data.get(x, {}).get('comments', 'N/A'))
        df_all_stats['shares'] = df_all_stats['video_id'].map(lambda x: all_stats_data.get(x, {}).get('shares', 'N/A'))
        df_all_stats['duration'] = df_all_stats['video_id'].map(lambda x: all_stats_data.get(x, {}).get('duration', 'N/A'))


        print("\nDataFrame with Views, Likes, Comments, AND Duration:")
        print(df_all_stats)
        print("-" * 30)

    else:
        print("No valid video IDs found in the DataFrame. No stats will be added.")
        df['views'] = 'N/A'
        df['likes'] = 'N/A'
        df['comments'] = 'N/A'
        df['shares'] = 'N/A'
        df['duration'] = 'N/A' # Add duration column even if no stats


    print("\nDataFrame with YouTube Stats:")
    print(df.head())

--- Fetching Views, Likes, Comments, AND Duration for 1262 unique video IDs ---

DataFrame with Views, Likes, Comments, AND Duration:
                                                   link  \
0     https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...
1     https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...
2     https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...
3     https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...
4     https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...
...                                                 ...
1270  https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...
1271  https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...
1272  https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...
1273  https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...
1274  https://www.1tv.am/hy/video/Հարցազրույց-Արսեն-...

                                             video_link  \
0     https://www.youtube.com/embed/gkLMht3Vt-k?auto...
1     https://www.youtube.com/embed/yjj8ISwxTwE?auto...
2     https://www.youtube.com/embed/Hd6l_IRhygI?auto...
3     https://www.youtube.com/embed/d5x7uI6cCLI?auto...
4     https://www.youtube.com/embed/gpIDqXFZx8o?auto...
...                                                 ...
1270  https://www.youtube.com/embed/6g5sFkYDopo?auto...
1271  https://www.youtube.com/embed/g_N7y10q5jE?auto...
1272  https://www.youtube.com/embed/PLfaKqneN8g?auto...
1273  https://www.youtube.com/embed/XA3jcUzjQRI?auto...
1274  https://www.youtube.com/embed/Mo-CuhQ4wNg?auto...

                                                  title   time          date  \
0                        Հարցազրույց Սոսի Թաթիկյանի հետ  22:10  03 Հլս, 2025
1                      Հարցազրույց Համբիկ Սարաֆյանի հետ  22:10  02 Հլս, 2025
2                           Հարցազրույց Կայա Կալասի հետ  22:10  01 Հլս, 2025
3                      Հարցազրույց Արթուր Պողոսյանի հետ  22:10  30 Հնս, 2025
4                        Հարցազրույց Էլեն Հոխիկյանի հետ  22:30  27 Հնս, 2025
...                                                 ...    ...           ...
1270  Հարցազրույց Պետրոս Ղազարյանի հետ. Կարեն Անդրեա...  19:30  06 Փտր, 2020
1271  Հարցազրույց Պետրոս Ղազարյանի հետ. Էդմոն Մարուքյան  19:30  05 Փտր, 2020
1272  Հարցազրույց Պետրոս Ղազարյանի հետ. Տիգրան Խաչատ...  19:30  04 Փտր, 2020
1273  Հարցազրույց Պետրոս Ղազարյանի հետ. Ռուբեն Ռուբի...  19:30  03 Փտր, 2020
1274                    Հարցազրույց Արսեն Թորոսյանի հետ  18:24  12 Հոկ, 2021

         video_id  views likes comments shares duration
0     gkLMht3Vt-k  33829   410        0    N/A      N/A
1     yjj8ISwxTwE  34014   518        0    N/A      N/A
2     Hd6l_IRhygI  42735   888        0    N/A      N/A
3     d5x7uI6cCLI  97811  1384        0    N/A      N/A
4     gpIDqXFZx8o  42024   504        0    N/A      N/A
...           ...    ...   ...      ...    ...      ...
1270  6g5sFkYDopo  30397   847      100    N/A      N/A
1271  g_N7y10q5jE   1801    20       14    N/A      N/A
1272  PLfaKqneN8g   2120    34        1    N/A      N/A
1273  XA3jcUzjQRI  15580   280       38    N/A      N/A
1274  Mo-CuhQ4wNg  14683   228        0    N/A      N/A

[1275 rows x 11 columns]
------------------------------

DataFrame with YouTube Stats:
                                                link  \
0  https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...
1  https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...
2  https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...
3  https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...
4  https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...

                                          video_link  \
0  https://www.youtube.com/embed/gkLMht3Vt-k?auto...
1  https://www.youtube.com/embed/yjj8ISwxTwE?auto...
2  https://www.youtube.com/embed/Hd6l_IRhygI?auto...
3  https://www.youtube.com/embed/d5x7uI6cCLI?auto...
4  https://www.youtube.com/embed/gpIDqXFZx8o?auto...

                              title   time          date     video_id  views  \
0    Հարցազրույց Սոսի Թաթիկյանի հետ  22:10  03 Հլս, 2025  gkLMht3Vt-k  33761
1  Հարցազրույց Համբիկ Սարաֆյանի հետ  22:10  02 Հլս, 2025  yjj8ISwxTwE  33991
2       Հարցազրույց Կայա Կալասի հետ  22:10  01 Հլս, 2025  Hd6l_IRhygI  42727
3  Հարցազրույց Արթուր Պողոսյանի հետ  22:10  30 Հնս, 2025  d5x7uI6cCLI  97758
4    Հարցազրույց Էլեն Հոխիկյանի հետ  22:30  27 Հնս, 2025  gpIDqXFZx8o  42014

  likes comments shares
0   410        0    N/A
1   518        0    N/A
2   888        0    N/A
3  1384        0    N/A
4   504        0    N/A

In [29]:
df

,link,video_link,title,time,date,video_id,views,likes,comments,shares
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025",gkLMht3Vt-k,33761,410,0,N/A
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025",yjj8ISwxTwE,33991,518,0,N/A
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025",Hd6l_IRhygI,42727,888,0,N/A
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025",d5x7uI6cCLI,97758,1384,0,N/A
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025",gpIDqXFZx8o,42014,504,0,N/A
...,...,...,...,...,...,...,...,...,...,...
1270,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/6g5sFkYDopo?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Կարեն Անդրեա...,19:30,"06 Փտր, 2020",6g5sFkYDopo,30397,847,100,N/A
1271,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/g_N7y10q5jE?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Էդմոն Մարուքյան,19:30,"05 Փտր, 2020",g_N7y10q5jE,1801,20,14,N/A
1272,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/PLfaKqneN8g?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Տիգրան Խաչատ...,19:30,"04 Փտր, 2020",PLfaKqneN8g,2119,34,1,N/A
1273,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/XA3jcUzjQRI?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Ռուբեն Ռուբի...,19:30,"03 Փտր, 2020",XA3jcUzjQRI,15580,280,38,N/A
1274,https://www.1tv.am/hy/video/Հարցազրույց-Արսեն-...,https://www.youtube.com/embed/Mo-CuhQ4wNg?auto...,Հարցազրույց Արսեն Թորոսյանի հետ,18:24,"12 Հոկ, 2021",Mo-CuhQ4wNg,14683,228,0,N/A

In [27]:
df

,link,video_link,title,time,date,video_id,views,likes,comments,shares
0,https://www.1tv.am/hy/video/Հարցազրույց-Սոսի-Թ...,https://www.youtube.com/embed/gkLMht3Vt-k?auto...,Հարցազրույց Սոսի Թաթիկյանի հետ,22:10,"03 Հլս, 2025",gkLMht3Vt-k,33761,410,0,N/A
1,https://www.1tv.am/hy/video/Հարցազրույց-Համբիկ...,https://www.youtube.com/embed/yjj8ISwxTwE?auto...,Հարցազրույց Համբիկ Սարաֆյանի հետ,22:10,"02 Հլս, 2025",yjj8ISwxTwE,33991,518,0,N/A
2,https://www.1tv.am/hy/video/Հարցազրույց-Կայա-Կ...,https://www.youtube.com/embed/Hd6l_IRhygI?auto...,Հարցազրույց Կայա Կալասի հետ,22:10,"01 Հլս, 2025",Hd6l_IRhygI,42727,888,0,N/A
3,https://www.1tv.am/hy/video/Հարցազրույց-Արթուր...,https://www.youtube.com/embed/d5x7uI6cCLI?auto...,Հարցազրույց Արթուր Պողոսյանի հետ,22:10,"30 Հնս, 2025",d5x7uI6cCLI,97758,1384,0,N/A
4,https://www.1tv.am/hy/video/Հարցազրույց-Էլեն-Հ...,https://www.youtube.com/embed/gpIDqXFZx8o?auto...,Հարցազրույց Էլեն Հոխիկյանի հետ,22:30,"27 Հնս, 2025",gpIDqXFZx8o,42014,504,0,N/A
...,...,...,...,...,...,...,...,...,...,...
1270,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/6g5sFkYDopo?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Կարեն Անդրեա...,19:30,"06 Փտր, 2020",6g5sFkYDopo,30397,847,100,N/A
1271,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/g_N7y10q5jE?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Էդմոն Մարուքյան,19:30,"05 Փտր, 2020",g_N7y10q5jE,1801,20,14,N/A
1272,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/PLfaKqneN8g?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Տիգրան Խաչատ...,19:30,"04 Փտր, 2020",PLfaKqneN8g,2119,34,1,N/A
1273,https://www.1tv.am/hy/video/Հարցազրույց-Պետրոս...,https://www.youtube.com/embed/XA3jcUzjQRI?auto...,Հարցազրույց Պետրոս Ղազարյանի հետ. Ռուբեն Ռուբի...,19:30,"03 Փտր, 2020",XA3jcUzjQRI,15580,280,38,N/A
1274,https://www.1tv.am/hy/video/Հարցազրույց-Արսեն-...,https://www.youtube.com/embed/Mo-CuhQ4wNg?auto...,Հարցազրույց Արսեն Թորոսյանի հետ,18:24,"12 Հոկ, 2021",Mo-CuhQ4wNg,14683,228,0,N/A